// Code generated by ent, DO NOT EDIT.

package appconfig

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the appconfig type in the database.
	Label = "app_config"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMikrotikAddress holds the string denoting the mikrotik_address field in the database.
	FieldMikrotikAddress = "mikrotik_address"
	// FieldMikrotikUsername holds the string denoting the mikrotik_username field in the database.
	FieldMikrotikUsername = "mikrotik_username"
	// FieldMikrotikPassword holds the string denoting the mikrotik_password field in the database.
	FieldMikrotikPassword = "mikrotik_password"
	// FieldOauthIssuer holds the string denoting the oauth_issuer field in the database.
	FieldOauthIssuer = "oauth_issuer"
	// FieldOauthAudience holds the string denoting the oauth_audience field in the database.
	FieldOauthAudience = "oauth_audience"
	// FieldVlanScope holds the string denoting the vlan_scope field in the database.
	FieldVlanScope = "vlan_scope"
	// FieldEnableAuthentication holds the string denoting the enable_authentication field in the database.
	FieldEnableAuthentication = "enable_authentication"
	// Table holds the table name of the appconfig in the database.
	Table = "app_configs"
)

// Columns holds all SQL columns for appconfig fields.
var Columns = []string{
	FieldID,
	FieldMikrotikAddress,
	FieldMikrotikUsername,
	FieldMikrotikPassword,
	FieldOauthIssuer,
	FieldOauthAudience,
	FieldVlanScope,
	FieldEnableAuthentication,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultEnableAuthentication holds the default value on creation for the "enable_authentication" field.
	DefaultEnableAuthentication bool
)

// OrderOption defines the ordering options for the AppConfig queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByMikrotikAddress orders the results by the mikrotik_address field.
func ByMikrotikAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMikrotikAddress, opts...).ToFunc()
}

// ByMikrotikUsername orders the results by the mikrotik_username field.
func ByMikrotikUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMikrotikUsername, opts...).ToFunc()
}

// ByMikrotikPassword orders the results by the mikrotik_password field.
func ByMikrotikPassword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMikrotikPassword, opts...).ToFunc()
}

// ByOauthIssuer orders the results by the oauth_issuer field.
func ByOauthIssuer(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOauthIssuer, opts...).ToFunc()
}

// ByOauthAudience orders the results by the oauth_audience field.
func ByOauthAudience(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOauthAudience, opts...).ToFunc()
}

// ByVlanScope orders the results by the vlan_scope field.
func ByVlanScope(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVlanScope, opts...).ToFunc()
}

// ByEnableAuthentication orders the results by the enable_authentication field.
func ByEnableAuthentication(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnableAuthentication, opts...).ToFunc()
}
