// Code generated by ent, DO NOT EDIT.

package appconfig

import (
	"go-mikrotik-vlan-switcher/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLTE(FieldID, id))
}

// MikrotikAddress applies equality check predicate on the "mikrotik_address" field. It's identical to MikrotikAddressEQ.
func MikrotikAddress(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldMikrotikAddress, v))
}

// MikrotikUsername applies equality check predicate on the "mikrotik_username" field. It's identical to MikrotikUsernameEQ.
func MikrotikUsername(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldMikrotikUsername, v))
}

// MikrotikPassword applies equality check predicate on the "mikrotik_password" field. It's identical to MikrotikPasswordEQ.
func MikrotikPassword(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldMikrotikPassword, v))
}

// OauthIssuer applies equality check predicate on the "oauth_issuer" field. It's identical to OauthIssuerEQ.
func OauthIssuer(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldOauthIssuer, v))
}

// OauthAudience applies equality check predicate on the "oauth_audience" field. It's identical to OauthAudienceEQ.
func OauthAudience(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldOauthAudience, v))
}

// VlanScope applies equality check predicate on the "vlan_scope" field. It's identical to VlanScopeEQ.
func VlanScope(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldVlanScope, v))
}

// EnableAuthentication applies equality check predicate on the "enable_authentication" field. It's identical to EnableAuthenticationEQ.
func EnableAuthentication(v bool) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldEnableAuthentication, v))
}

// MikrotikAddressEQ applies the EQ predicate on the "mikrotik_address" field.
func MikrotikAddressEQ(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldMikrotikAddress, v))
}

// MikrotikAddressNEQ applies the NEQ predicate on the "mikrotik_address" field.
func MikrotikAddressNEQ(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNEQ(FieldMikrotikAddress, v))
}

// MikrotikAddressIn applies the In predicate on the "mikrotik_address" field.
func MikrotikAddressIn(vs ...string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIn(FieldMikrotikAddress, vs...))
}

// MikrotikAddressNotIn applies the NotIn predicate on the "mikrotik_address" field.
func MikrotikAddressNotIn(vs ...string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotIn(FieldMikrotikAddress, vs...))
}

// MikrotikAddressGT applies the GT predicate on the "mikrotik_address" field.
func MikrotikAddressGT(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGT(FieldMikrotikAddress, v))
}

// MikrotikAddressGTE applies the GTE predicate on the "mikrotik_address" field.
func MikrotikAddressGTE(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGTE(FieldMikrotikAddress, v))
}

// MikrotikAddressLT applies the LT predicate on the "mikrotik_address" field.
func MikrotikAddressLT(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLT(FieldMikrotikAddress, v))
}

// MikrotikAddressLTE applies the LTE predicate on the "mikrotik_address" field.
func MikrotikAddressLTE(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLTE(FieldMikrotikAddress, v))
}

// MikrotikAddressContains applies the Contains predicate on the "mikrotik_address" field.
func MikrotikAddressContains(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldContains(FieldMikrotikAddress, v))
}

// MikrotikAddressHasPrefix applies the HasPrefix predicate on the "mikrotik_address" field.
func MikrotikAddressHasPrefix(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldHasPrefix(FieldMikrotikAddress, v))
}

// MikrotikAddressHasSuffix applies the HasSuffix predicate on the "mikrotik_address" field.
func MikrotikAddressHasSuffix(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldHasSuffix(FieldMikrotikAddress, v))
}

// MikrotikAddressEqualFold applies the EqualFold predicate on the "mikrotik_address" field.
func MikrotikAddressEqualFold(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEqualFold(FieldMikrotikAddress, v))
}

// MikrotikAddressContainsFold applies the ContainsFold predicate on the "mikrotik_address" field.
func MikrotikAddressContainsFold(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldContainsFold(FieldMikrotikAddress, v))
}

// MikrotikUsernameEQ applies the EQ predicate on the "mikrotik_username" field.
func MikrotikUsernameEQ(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldMikrotikUsername, v))
}

// MikrotikUsernameNEQ applies the NEQ predicate on the "mikrotik_username" field.
func MikrotikUsernameNEQ(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNEQ(FieldMikrotikUsername, v))
}

// MikrotikUsernameIn applies the In predicate on the "mikrotik_username" field.
func MikrotikUsernameIn(vs ...string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIn(FieldMikrotikUsername, vs...))
}

// MikrotikUsernameNotIn applies the NotIn predicate on the "mikrotik_username" field.
func MikrotikUsernameNotIn(vs ...string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotIn(FieldMikrotikUsername, vs...))
}

// MikrotikUsernameGT applies the GT predicate on the "mikrotik_username" field.
func MikrotikUsernameGT(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGT(FieldMikrotikUsername, v))
}

// MikrotikUsernameGTE applies the GTE predicate on the "mikrotik_username" field.
func MikrotikUsernameGTE(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGTE(FieldMikrotikUsername, v))
}

// MikrotikUsernameLT applies the LT predicate on the "mikrotik_username" field.
func MikrotikUsernameLT(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLT(FieldMikrotikUsername, v))
}

// MikrotikUsernameLTE applies the LTE predicate on the "mikrotik_username" field.
func MikrotikUsernameLTE(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLTE(FieldMikrotikUsername, v))
}

// MikrotikUsernameContains applies the Contains predicate on the "mikrotik_username" field.
func MikrotikUsernameContains(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldContains(FieldMikrotikUsername, v))
}

// MikrotikUsernameHasPrefix applies the HasPrefix predicate on the "mikrotik_username" field.
func MikrotikUsernameHasPrefix(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldHasPrefix(FieldMikrotikUsername, v))
}

// MikrotikUsernameHasSuffix applies the HasSuffix predicate on the "mikrotik_username" field.
func MikrotikUsernameHasSuffix(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldHasSuffix(FieldMikrotikUsername, v))
}

// MikrotikUsernameEqualFold applies the EqualFold predicate on the "mikrotik_username" field.
func MikrotikUsernameEqualFold(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEqualFold(FieldMikrotikUsername, v))
}

// MikrotikUsernameContainsFold applies the ContainsFold predicate on the "mikrotik_username" field.
func MikrotikUsernameContainsFold(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldContainsFold(FieldMikrotikUsername, v))
}

// MikrotikPasswordEQ applies the EQ predicate on the "mikrotik_password" field.
func MikrotikPasswordEQ(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldMikrotikPassword, v))
}

// MikrotikPasswordNEQ applies the NEQ predicate on the "mikrotik_password" field.
func MikrotikPasswordNEQ(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNEQ(FieldMikrotikPassword, v))
}

// MikrotikPasswordIn applies the In predicate on the "mikrotik_password" field.
func MikrotikPasswordIn(vs ...string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIn(FieldMikrotikPassword, vs...))
}

// MikrotikPasswordNotIn applies the NotIn predicate on the "mikrotik_password" field.
func MikrotikPasswordNotIn(vs ...string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotIn(FieldMikrotikPassword, vs...))
}

// MikrotikPasswordGT applies the GT predicate on the "mikrotik_password" field.
func MikrotikPasswordGT(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGT(FieldMikrotikPassword, v))
}

// MikrotikPasswordGTE applies the GTE predicate on the "mikrotik_password" field.
func MikrotikPasswordGTE(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGTE(FieldMikrotikPassword, v))
}

// MikrotikPasswordLT applies the LT predicate on the "mikrotik_password" field.
func MikrotikPasswordLT(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLT(FieldMikrotikPassword, v))
}

// MikrotikPasswordLTE applies the LTE predicate on the "mikrotik_password" field.
func MikrotikPasswordLTE(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLTE(FieldMikrotikPassword, v))
}

// MikrotikPasswordContains applies the Contains predicate on the "mikrotik_password" field.
func MikrotikPasswordContains(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldContains(FieldMikrotikPassword, v))
}

// MikrotikPasswordHasPrefix applies the HasPrefix predicate on the "mikrotik_password" field.
func MikrotikPasswordHasPrefix(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldHasPrefix(FieldMikrotikPassword, v))
}

// MikrotikPasswordHasSuffix applies the HasSuffix predicate on the "mikrotik_password" field.
func MikrotikPasswordHasSuffix(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldHasSuffix(FieldMikrotikPassword, v))
}

// MikrotikPasswordEqualFold applies the EqualFold predicate on the "mikrotik_password" field.
func MikrotikPasswordEqualFold(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEqualFold(FieldMikrotikPassword, v))
}

// MikrotikPasswordContainsFold applies the ContainsFold predicate on the "mikrotik_password" field.
func MikrotikPasswordContainsFold(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldContainsFold(FieldMikrotikPassword, v))
}

// OauthIssuerEQ applies the EQ predicate on the "oauth_issuer" field.
func OauthIssuerEQ(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldOauthIssuer, v))
}

// OauthIssuerNEQ applies the NEQ predicate on the "oauth_issuer" field.
func OauthIssuerNEQ(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNEQ(FieldOauthIssuer, v))
}

// OauthIssuerIn applies the In predicate on the "oauth_issuer" field.
func OauthIssuerIn(vs ...string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIn(FieldOauthIssuer, vs...))
}

// OauthIssuerNotIn applies the NotIn predicate on the "oauth_issuer" field.
func OauthIssuerNotIn(vs ...string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotIn(FieldOauthIssuer, vs...))
}

// OauthIssuerGT applies the GT predicate on the "oauth_issuer" field.
func OauthIssuerGT(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGT(FieldOauthIssuer, v))
}

// OauthIssuerGTE applies the GTE predicate on the "oauth_issuer" field.
func OauthIssuerGTE(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGTE(FieldOauthIssuer, v))
}

// OauthIssuerLT applies the LT predicate on the "oauth_issuer" field.
func OauthIssuerLT(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLT(FieldOauthIssuer, v))
}

// OauthIssuerLTE applies the LTE predicate on the "oauth_issuer" field.
func OauthIssuerLTE(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLTE(FieldOauthIssuer, v))
}

// OauthIssuerContains applies the Contains predicate on the "oauth_issuer" field.
func OauthIssuerContains(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldContains(FieldOauthIssuer, v))
}

// OauthIssuerHasPrefix applies the HasPrefix predicate on the "oauth_issuer" field.
func OauthIssuerHasPrefix(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldHasPrefix(FieldOauthIssuer, v))
}

// OauthIssuerHasSuffix applies the HasSuffix predicate on the "oauth_issuer" field.
func OauthIssuerHasSuffix(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldHasSuffix(FieldOauthIssuer, v))
}

// OauthIssuerEqualFold applies the EqualFold predicate on the "oauth_issuer" field.
func OauthIssuerEqualFold(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEqualFold(FieldOauthIssuer, v))
}

// OauthIssuerContainsFold applies the ContainsFold predicate on the "oauth_issuer" field.
func OauthIssuerContainsFold(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldContainsFold(FieldOauthIssuer, v))
}

// OauthAudienceEQ applies the EQ predicate on the "oauth_audience" field.
func OauthAudienceEQ(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldOauthAudience, v))
}

// OauthAudienceNEQ applies the NEQ predicate on the "oauth_audience" field.
func OauthAudienceNEQ(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNEQ(FieldOauthAudience, v))
}

// OauthAudienceIn applies the In predicate on the "oauth_audience" field.
func OauthAudienceIn(vs ...string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIn(FieldOauthAudience, vs...))
}

// OauthAudienceNotIn applies the NotIn predicate on the "oauth_audience" field.
func OauthAudienceNotIn(vs ...string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotIn(FieldOauthAudience, vs...))
}

// OauthAudienceGT applies the GT predicate on the "oauth_audience" field.
func OauthAudienceGT(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGT(FieldOauthAudience, v))
}

// OauthAudienceGTE applies the GTE predicate on the "oauth_audience" field.
func OauthAudienceGTE(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGTE(FieldOauthAudience, v))
}

// OauthAudienceLT applies the LT predicate on the "oauth_audience" field.
func OauthAudienceLT(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLT(FieldOauthAudience, v))
}

// OauthAudienceLTE applies the LTE predicate on the "oauth_audience" field.
func OauthAudienceLTE(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLTE(FieldOauthAudience, v))
}

// OauthAudienceContains applies the Contains predicate on the "oauth_audience" field.
func OauthAudienceContains(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldContains(FieldOauthAudience, v))
}

// OauthAudienceHasPrefix applies the HasPrefix predicate on the "oauth_audience" field.
func OauthAudienceHasPrefix(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldHasPrefix(FieldOauthAudience, v))
}

// OauthAudienceHasSuffix applies the HasSuffix predicate on the "oauth_audience" field.
func OauthAudienceHasSuffix(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldHasSuffix(FieldOauthAudience, v))
}

// OauthAudienceEqualFold applies the EqualFold predicate on the "oauth_audience" field.
func OauthAudienceEqualFold(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEqualFold(FieldOauthAudience, v))
}

// OauthAudienceContainsFold applies the ContainsFold predicate on the "oauth_audience" field.
func OauthAudienceContainsFold(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldContainsFold(FieldOauthAudience, v))
}

// VlanScopeEQ applies the EQ predicate on the "vlan_scope" field.
func VlanScopeEQ(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldVlanScope, v))
}

// VlanScopeNEQ applies the NEQ predicate on the "vlan_scope" field.
func VlanScopeNEQ(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNEQ(FieldVlanScope, v))
}

// VlanScopeIn applies the In predicate on the "vlan_scope" field.
func VlanScopeIn(vs ...string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldIn(FieldVlanScope, vs...))
}

// VlanScopeNotIn applies the NotIn predicate on the "vlan_scope" field.
func VlanScopeNotIn(vs ...string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNotIn(FieldVlanScope, vs...))
}

// VlanScopeGT applies the GT predicate on the "vlan_scope" field.
func VlanScopeGT(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGT(FieldVlanScope, v))
}

// VlanScopeGTE applies the GTE predicate on the "vlan_scope" field.
func VlanScopeGTE(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldGTE(FieldVlanScope, v))
}

// VlanScopeLT applies the LT predicate on the "vlan_scope" field.
func VlanScopeLT(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLT(FieldVlanScope, v))
}

// VlanScopeLTE applies the LTE predicate on the "vlan_scope" field.
func VlanScopeLTE(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldLTE(FieldVlanScope, v))
}

// VlanScopeContains applies the Contains predicate on the "vlan_scope" field.
func VlanScopeContains(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldContains(FieldVlanScope, v))
}

// VlanScopeHasPrefix applies the HasPrefix predicate on the "vlan_scope" field.
func VlanScopeHasPrefix(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldHasPrefix(FieldVlanScope, v))
}

// VlanScopeHasSuffix applies the HasSuffix predicate on the "vlan_scope" field.
func VlanScopeHasSuffix(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldHasSuffix(FieldVlanScope, v))
}

// VlanScopeEqualFold applies the EqualFold predicate on the "vlan_scope" field.
func VlanScopeEqualFold(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEqualFold(FieldVlanScope, v))
}

// VlanScopeContainsFold applies the ContainsFold predicate on the "vlan_scope" field.
func VlanScopeContainsFold(v string) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldContainsFold(FieldVlanScope, v))
}

// EnableAuthenticationEQ applies the EQ predicate on the "enable_authentication" field.
func EnableAuthenticationEQ(v bool) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldEQ(FieldEnableAuthentication, v))
}

// EnableAuthenticationNEQ applies the NEQ predicate on the "enable_authentication" field.
func EnableAuthenticationNEQ(v bool) predicate.AppConfig {
	return predicate.AppConfig(sql.FieldNEQ(FieldEnableAuthentication, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AppConfig) predicate.AppConfig {
	return predicate.AppConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AppConfig) predicate.AppConfig {
	return predicate.AppConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AppConfig) predicate.AppConfig {
	return predicate.AppConfig(sql.NotPredicates(p))
}
