// Code generated by ent, DO NOT EDIT.

package interfacevlanstate

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the interfacevlanstate type in the database.
	Label = "interface_vlan_state"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldInterface holds the string denoting the interface field in the database.
	FieldInterface = "interface"
	// FieldCurrentList holds the string denoting the current_list field in the database.
	FieldCurrentList = "current_list"
	// FieldCurrentVlanID holds the string denoting the current_vlan_id field in the database.
	FieldCurrentVlanID = "current_vlan_id"
	// FieldLastSyncedAt holds the string denoting the last_synced_at field in the database.
	FieldLastSyncedAt = "last_synced_at"
	// Table holds the table name of the interfacevlanstate in the database.
	Table = "interface_vlan_states"
)

// Columns holds all SQL columns for interfacevlanstate fields.
var Columns = []string{
	FieldID,
	FieldInterface,
	FieldCurrentList,
	FieldCurrentVlanID,
	FieldLastSyncedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultLastSyncedAt holds the default value on creation for the "last_synced_at" field.
	DefaultLastSyncedAt func() time.Time
	// UpdateDefaultLastSyncedAt holds the default value on update for the "last_synced_at" field.
	UpdateDefaultLastSyncedAt func() time.Time
)

// OrderOption defines the ordering options for the InterfaceVlanState queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByInterface orders the results by the interface field.
func ByInterface(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInterface, opts...).ToFunc()
}

// ByCurrentList orders the results by the current_list field.
func ByCurrentList(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentList, opts...).ToFunc()
}

// ByCurrentVlanID orders the results by the current_vlan_id field.
func ByCurrentVlanID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentVlanID, opts...).ToFunc()
}

// ByLastSyncedAt orders the results by the last_synced_at field.
func ByLastSyncedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSyncedAt, opts...).ToFunc()
}
