// Code generated by ent, DO NOT EDIT.

package interfacevlanstate

import (
	"go-mikrotik-vlan-switcher/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldLTE(FieldID, id))
}

// Interface applies equality check predicate on the "interface" field. It's identical to InterfaceEQ.
func Interface(v string) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldEQ(FieldInterface, v))
}

// CurrentList applies equality check predicate on the "current_list" field. It's identical to CurrentListEQ.
func CurrentList(v string) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldEQ(FieldCurrentList, v))
}

// CurrentVlanID applies equality check predicate on the "current_vlan_id" field. It's identical to CurrentVlanIDEQ.
func CurrentVlanID(v int) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldEQ(FieldCurrentVlanID, v))
}

// LastSyncedAt applies equality check predicate on the "last_synced_at" field. It's identical to LastSyncedAtEQ.
func LastSyncedAt(v time.Time) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldEQ(FieldLastSyncedAt, v))
}

// InterfaceEQ applies the EQ predicate on the "interface" field.
func InterfaceEQ(v string) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldEQ(FieldInterface, v))
}

// InterfaceNEQ applies the NEQ predicate on the "interface" field.
func InterfaceNEQ(v string) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldNEQ(FieldInterface, v))
}

// InterfaceIn applies the In predicate on the "interface" field.
func InterfaceIn(vs ...string) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldIn(FieldInterface, vs...))
}

// InterfaceNotIn applies the NotIn predicate on the "interface" field.
func InterfaceNotIn(vs ...string) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldNotIn(FieldInterface, vs...))
}

// InterfaceGT applies the GT predicate on the "interface" field.
func InterfaceGT(v string) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldGT(FieldInterface, v))
}

// InterfaceGTE applies the GTE predicate on the "interface" field.
func InterfaceGTE(v string) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldGTE(FieldInterface, v))
}

// InterfaceLT applies the LT predicate on the "interface" field.
func InterfaceLT(v string) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldLT(FieldInterface, v))
}

// InterfaceLTE applies the LTE predicate on the "interface" field.
func InterfaceLTE(v string) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldLTE(FieldInterface, v))
}

// InterfaceContains applies the Contains predicate on the "interface" field.
func InterfaceContains(v string) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldContains(FieldInterface, v))
}

// InterfaceHasPrefix applies the HasPrefix predicate on the "interface" field.
func InterfaceHasPrefix(v string) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldHasPrefix(FieldInterface, v))
}

// InterfaceHasSuffix applies the HasSuffix predicate on the "interface" field.
func InterfaceHasSuffix(v string) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldHasSuffix(FieldInterface, v))
}

// InterfaceEqualFold applies the EqualFold predicate on the "interface" field.
func InterfaceEqualFold(v string) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldEqualFold(FieldInterface, v))
}

// InterfaceContainsFold applies the ContainsFold predicate on the "interface" field.
func InterfaceContainsFold(v string) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldContainsFold(FieldInterface, v))
}

// CurrentListEQ applies the EQ predicate on the "current_list" field.
func CurrentListEQ(v string) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldEQ(FieldCurrentList, v))
}

// CurrentListNEQ applies the NEQ predicate on the "current_list" field.
func CurrentListNEQ(v string) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldNEQ(FieldCurrentList, v))
}

// CurrentListIn applies the In predicate on the "current_list" field.
func CurrentListIn(vs ...string) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldIn(FieldCurrentList, vs...))
}

// CurrentListNotIn applies the NotIn predicate on the "current_list" field.
func CurrentListNotIn(vs ...string) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldNotIn(FieldCurrentList, vs...))
}

// CurrentListGT applies the GT predicate on the "current_list" field.
func CurrentListGT(v string) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldGT(FieldCurrentList, v))
}

// CurrentListGTE applies the GTE predicate on the "current_list" field.
func CurrentListGTE(v string) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldGTE(FieldCurrentList, v))
}

// CurrentListLT applies the LT predicate on the "current_list" field.
func CurrentListLT(v string) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldLT(FieldCurrentList, v))
}

// CurrentListLTE applies the LTE predicate on the "current_list" field.
func CurrentListLTE(v string) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldLTE(FieldCurrentList, v))
}

// CurrentListContains applies the Contains predicate on the "current_list" field.
func CurrentListContains(v string) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldContains(FieldCurrentList, v))
}

// CurrentListHasPrefix applies the HasPrefix predicate on the "current_list" field.
func CurrentListHasPrefix(v string) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldHasPrefix(FieldCurrentList, v))
}

// CurrentListHasSuffix applies the HasSuffix predicate on the "current_list" field.
func CurrentListHasSuffix(v string) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldHasSuffix(FieldCurrentList, v))
}

// CurrentListEqualFold applies the EqualFold predicate on the "current_list" field.
func CurrentListEqualFold(v string) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldEqualFold(FieldCurrentList, v))
}

// CurrentListContainsFold applies the ContainsFold predicate on the "current_list" field.
func CurrentListContainsFold(v string) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldContainsFold(FieldCurrentList, v))
}

// CurrentVlanIDEQ applies the EQ predicate on the "current_vlan_id" field.
func CurrentVlanIDEQ(v int) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldEQ(FieldCurrentVlanID, v))
}

// CurrentVlanIDNEQ applies the NEQ predicate on the "current_vlan_id" field.
func CurrentVlanIDNEQ(v int) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldNEQ(FieldCurrentVlanID, v))
}

// CurrentVlanIDIn applies the In predicate on the "current_vlan_id" field.
func CurrentVlanIDIn(vs ...int) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldIn(FieldCurrentVlanID, vs...))
}

// CurrentVlanIDNotIn applies the NotIn predicate on the "current_vlan_id" field.
func CurrentVlanIDNotIn(vs ...int) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldNotIn(FieldCurrentVlanID, vs...))
}

// CurrentVlanIDGT applies the GT predicate on the "current_vlan_id" field.
func CurrentVlanIDGT(v int) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldGT(FieldCurrentVlanID, v))
}

// CurrentVlanIDGTE applies the GTE predicate on the "current_vlan_id" field.
func CurrentVlanIDGTE(v int) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldGTE(FieldCurrentVlanID, v))
}

// CurrentVlanIDLT applies the LT predicate on the "current_vlan_id" field.
func CurrentVlanIDLT(v int) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldLT(FieldCurrentVlanID, v))
}

// CurrentVlanIDLTE applies the LTE predicate on the "current_vlan_id" field.
func CurrentVlanIDLTE(v int) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldLTE(FieldCurrentVlanID, v))
}

// LastSyncedAtEQ applies the EQ predicate on the "last_synced_at" field.
func LastSyncedAtEQ(v time.Time) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldEQ(FieldLastSyncedAt, v))
}

// LastSyncedAtNEQ applies the NEQ predicate on the "last_synced_at" field.
func LastSyncedAtNEQ(v time.Time) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldNEQ(FieldLastSyncedAt, v))
}

// LastSyncedAtIn applies the In predicate on the "last_synced_at" field.
func LastSyncedAtIn(vs ...time.Time) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldIn(FieldLastSyncedAt, vs...))
}

// LastSyncedAtNotIn applies the NotIn predicate on the "last_synced_at" field.
func LastSyncedAtNotIn(vs ...time.Time) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldNotIn(FieldLastSyncedAt, vs...))
}

// LastSyncedAtGT applies the GT predicate on the "last_synced_at" field.
func LastSyncedAtGT(v time.Time) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldGT(FieldLastSyncedAt, v))
}

// LastSyncedAtGTE applies the GTE predicate on the "last_synced_at" field.
func LastSyncedAtGTE(v time.Time) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldGTE(FieldLastSyncedAt, v))
}

// LastSyncedAtLT applies the LT predicate on the "last_synced_at" field.
func LastSyncedAtLT(v time.Time) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldLT(FieldLastSyncedAt, v))
}

// LastSyncedAtLTE applies the LTE predicate on the "last_synced_at" field.
func LastSyncedAtLTE(v time.Time) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.FieldLTE(FieldLastSyncedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InterfaceVlanState) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InterfaceVlanState) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InterfaceVlanState) predicate.InterfaceVlanState {
	return predicate.InterfaceVlanState(sql.NotPredicates(p))
}
