// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AppConfigsColumns holds the columns for the "app_configs" table.
	AppConfigsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "mikrotik_address", Type: field.TypeString},
		{Name: "mikrotik_username", Type: field.TypeString},
		{Name: "mikrotik_password", Type: field.TypeString},
		{Name: "oauth_issuer", Type: field.TypeString},
		{Name: "oauth_audience", Type: field.TypeString},
		{Name: "vlan_scope", Type: field.TypeString},
		{Name: "enable_authentication", Type: field.TypeBool, Default: true},
	}
	// AppConfigsTable holds the schema information for the "app_configs" table.
	AppConfigsTable = &schema.Table{
		Name:       "app_configs",
		Columns:    AppConfigsColumns,
		PrimaryKey: []*schema.Column{AppConfigsColumns[0]},
	}
	// InterfaceVlanStatesColumns holds the columns for the "interface_vlan_states" table.
	InterfaceVlanStatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "interface", Type: field.TypeString, Unique: true},
		{Name: "current_list", Type: field.TypeString},
		{Name: "current_vlan_id", Type: field.TypeInt},
		{Name: "last_synced_at", Type: field.TypeTime},
	}
	// InterfaceVlanStatesTable holds the schema information for the "interface_vlan_states" table.
	InterfaceVlanStatesTable = &schema.Table{
		Name:       "interface_vlan_states",
		Columns:    InterfaceVlanStatesColumns,
		PrimaryKey: []*schema.Column{InterfaceVlanStatesColumns[0]},
	}
	// RequestLogsColumns holds the columns for the "request_logs" table.
	RequestLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "timestamp", Type: field.TypeTime},
		{Name: "method", Type: field.TypeString},
		{Name: "path", Type: field.TypeString},
		{Name: "remote_addr", Type: field.TypeString},
		{Name: "subject", Type: field.TypeString, Nullable: true},
		{Name: "interface", Type: field.TypeString, Nullable: true},
		{Name: "vlan_id", Type: field.TypeInt, Nullable: true},
		{Name: "status_code", Type: field.TypeInt},
		{Name: "duration_ms", Type: field.TypeInt64},
		{Name: "error", Type: field.TypeString, Nullable: true},
	}
	// RequestLogsTable holds the schema information for the "request_logs" table.
	RequestLogsTable = &schema.Table{
		Name:       "request_logs",
		Columns:    RequestLogsColumns,
		PrimaryKey: []*schema.Column{RequestLogsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AppConfigsTable,
		InterfaceVlanStatesTable,
		RequestLogsTable,
	}
)

func init() {
}
