// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"go-mikrotik-vlan-switcher/ent/appconfig"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// AppConfig is the model entity for the AppConfig schema.
type AppConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// MikrotikAddress holds the value of the "mikrotik_address" field.
	MikrotikAddress string `json:"mikrotik_address,omitempty"`
	// MikrotikUsername holds the value of the "mikrotik_username" field.
	MikrotikUsername string `json:"mikrotik_username,omitempty"`
	// MikrotikPassword holds the value of the "mikrotik_password" field.
	MikrotikPassword string `json:"-"`
	// OauthIssuer holds the value of the "oauth_issuer" field.
	OauthIssuer string `json:"oauth_issuer,omitempty"`
	// OauthAudience holds the value of the "oauth_audience" field.
	OauthAudience string `json:"oauth_audience,omitempty"`
	// VlanScope holds the value of the "vlan_scope" field.
	VlanScope string `json:"vlan_scope,omitempty"`
	// EnableAuthentication holds the value of the "enable_authentication" field.
	EnableAuthentication bool `json:"enable_authentication,omitempty"`
	selectValues         sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AppConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case appconfig.FieldEnableAuthentication:
			values[i] = new(sql.NullBool)
		case appconfig.FieldID:
			values[i] = new(sql.NullInt64)
		case appconfig.FieldMikrotikAddress, appconfig.FieldMikrotikUsername, appconfig.FieldMikrotikPassword, appconfig.FieldOauthIssuer, appconfig.FieldOauthAudience, appconfig.FieldVlanScope:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AppConfig fields.
func (_m *AppConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case appconfig.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case appconfig.FieldMikrotikAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mikrotik_address", values[i])
			} else if value.Valid {
				_m.MikrotikAddress = value.String
			}
		case appconfig.FieldMikrotikUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mikrotik_username", values[i])
			} else if value.Valid {
				_m.MikrotikUsername = value.String
			}
		case appconfig.FieldMikrotikPassword:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mikrotik_password", values[i])
			} else if value.Valid {
				_m.MikrotikPassword = value.String
			}
		case appconfig.FieldOauthIssuer:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field oauth_issuer", values[i])
			} else if value.Valid {
				_m.OauthIssuer = value.String
			}
		case appconfig.FieldOauthAudience:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field oauth_audience", values[i])
			} else if value.Valid {
				_m.OauthAudience = value.String
			}
		case appconfig.FieldVlanScope:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field vlan_scope", values[i])
			} else if value.Valid {
				_m.VlanScope = value.String
			}
		case appconfig.FieldEnableAuthentication:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enable_authentication", values[i])
			} else if value.Valid {
				_m.EnableAuthentication = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AppConfig.
// This includes values selected through modifiers, order, etc.
func (_m *AppConfig) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AppConfig.
// Note that you need to call AppConfig.Unwrap() before calling this method if this AppConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AppConfig) Update() *AppConfigUpdateOne {
	return NewAppConfigClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AppConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AppConfig) Unwrap() *AppConfig {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AppConfig is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AppConfig) String() string {
	var builder strings.Builder
	builder.WriteString("AppConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("mikrotik_address=")
	builder.WriteString(_m.MikrotikAddress)
	builder.WriteString(", ")
	builder.WriteString("mikrotik_username=")
	builder.WriteString(_m.MikrotikUsername)
	builder.WriteString(", ")
	builder.WriteString("mikrotik_password=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("oauth_issuer=")
	builder.WriteString(_m.OauthIssuer)
	builder.WriteString(", ")
	builder.WriteString("oauth_audience=")
	builder.WriteString(_m.OauthAudience)
	builder.WriteString(", ")
	builder.WriteString("vlan_scope=")
	builder.WriteString(_m.VlanScope)
	builder.WriteString(", ")
	builder.WriteString("enable_authentication=")
	builder.WriteString(fmt.Sprintf("%v", _m.EnableAuthentication))
	builder.WriteByte(')')
	return builder.String()
}

// AppConfigs is a parsable slice of AppConfig.
type AppConfigs []*AppConfig
