// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-mikrotik-vlan-switcher/ent/appconfig"
	"go-mikrotik-vlan-switcher/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AppConfigUpdate is the builder for updating AppConfig entities.
type AppConfigUpdate struct {
	config
	hooks    []Hook
	mutation *AppConfigMutation
}

// Where appends a list predicates to the AppConfigUpdate builder.
func (_u *AppConfigUpdate) Where(ps ...predicate.AppConfig) *AppConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMikrotikAddress sets the "mikrotik_address" field.
func (_u *AppConfigUpdate) SetMikrotikAddress(v string) *AppConfigUpdate {
	_u.mutation.SetMikrotikAddress(v)
	return _u
}

// SetNillableMikrotikAddress sets the "mikrotik_address" field if the given value is not nil.
func (_u *AppConfigUpdate) SetNillableMikrotikAddress(v *string) *AppConfigUpdate {
	if v != nil {
		_u.SetMikrotikAddress(*v)
	}
	return _u
}

// SetMikrotikUsername sets the "mikrotik_username" field.
func (_u *AppConfigUpdate) SetMikrotikUsername(v string) *AppConfigUpdate {
	_u.mutation.SetMikrotikUsername(v)
	return _u
}

// SetNillableMikrotikUsername sets the "mikrotik_username" field if the given value is not nil.
func (_u *AppConfigUpdate) SetNillableMikrotikUsername(v *string) *AppConfigUpdate {
	if v != nil {
		_u.SetMikrotikUsername(*v)
	}
	return _u
}

// SetMikrotikPassword sets the "mikrotik_password" field.
func (_u *AppConfigUpdate) SetMikrotikPassword(v string) *AppConfigUpdate {
	_u.mutation.SetMikrotikPassword(v)
	return _u
}

// SetNillableMikrotikPassword sets the "mikrotik_password" field if the given value is not nil.
func (_u *AppConfigUpdate) SetNillableMikrotikPassword(v *string) *AppConfigUpdate {
	if v != nil {
		_u.SetMikrotikPassword(*v)
	}
	return _u
}

// SetOauthIssuer sets the "oauth_issuer" field.
func (_u *AppConfigUpdate) SetOauthIssuer(v string) *AppConfigUpdate {
	_u.mutation.SetOauthIssuer(v)
	return _u
}

// SetNillableOauthIssuer sets the "oauth_issuer" field if the given value is not nil.
func (_u *AppConfigUpdate) SetNillableOauthIssuer(v *string) *AppConfigUpdate {
	if v != nil {
		_u.SetOauthIssuer(*v)
	}
	return _u
}

// SetOauthAudience sets the "oauth_audience" field.
func (_u *AppConfigUpdate) SetOauthAudience(v string) *AppConfigUpdate {
	_u.mutation.SetOauthAudience(v)
	return _u
}

// SetNillableOauthAudience sets the "oauth_audience" field if the given value is not nil.
func (_u *AppConfigUpdate) SetNillableOauthAudience(v *string) *AppConfigUpdate {
	if v != nil {
		_u.SetOauthAudience(*v)
	}
	return _u
}

// SetVlanScope sets the "vlan_scope" field.
func (_u *AppConfigUpdate) SetVlanScope(v string) *AppConfigUpdate {
	_u.mutation.SetVlanScope(v)
	return _u
}

// SetNillableVlanScope sets the "vlan_scope" field if the given value is not nil.
func (_u *AppConfigUpdate) SetNillableVlanScope(v *string) *AppConfigUpdate {
	if v != nil {
		_u.SetVlanScope(*v)
	}
	return _u
}

// SetEnableAuthentication sets the "enable_authentication" field.
func (_u *AppConfigUpdate) SetEnableAuthentication(v bool) *AppConfigUpdate {
	_u.mutation.SetEnableAuthentication(v)
	return _u
}

// SetNillableEnableAuthentication sets the "enable_authentication" field if the given value is not nil.
func (_u *AppConfigUpdate) SetNillableEnableAuthentication(v *bool) *AppConfigUpdate {
	if v != nil {
		_u.SetEnableAuthentication(*v)
	}
	return _u
}

// Mutation returns the AppConfigMutation object of the builder.
func (_u *AppConfigUpdate) Mutation() *AppConfigMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AppConfigUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AppConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AppConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AppConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AppConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(appconfig.Table, appconfig.Columns, sqlgraph.NewFieldSpec(appconfig.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MikrotikAddress(); ok {
		_spec.SetField(appconfig.FieldMikrotikAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.MikrotikUsername(); ok {
		_spec.SetField(appconfig.FieldMikrotikUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.MikrotikPassword(); ok {
		_spec.SetField(appconfig.FieldMikrotikPassword, field.TypeString, value)
	}
	if value, ok := _u.mutation.OauthIssuer(); ok {
		_spec.SetField(appconfig.FieldOauthIssuer, field.TypeString, value)
	}
	if value, ok := _u.mutation.OauthAudience(); ok {
		_spec.SetField(appconfig.FieldOauthAudience, field.TypeString, value)
	}
	if value, ok := _u.mutation.VlanScope(); ok {
		_spec.SetField(appconfig.FieldVlanScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.EnableAuthentication(); ok {
		_spec.SetField(appconfig.FieldEnableAuthentication, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{appconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AppConfigUpdateOne is the builder for updating a single AppConfig entity.
type AppConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AppConfigMutation
}

// SetMikrotikAddress sets the "mikrotik_address" field.
func (_u *AppConfigUpdateOne) SetMikrotikAddress(v string) *AppConfigUpdateOne {
	_u.mutation.SetMikrotikAddress(v)
	return _u
}

// SetNillableMikrotikAddress sets the "mikrotik_address" field if the given value is not nil.
func (_u *AppConfigUpdateOne) SetNillableMikrotikAddress(v *string) *AppConfigUpdateOne {
	if v != nil {
		_u.SetMikrotikAddress(*v)
	}
	return _u
}

// SetMikrotikUsername sets the "mikrotik_username" field.
func (_u *AppConfigUpdateOne) SetMikrotikUsername(v string) *AppConfigUpdateOne {
	_u.mutation.SetMikrotikUsername(v)
	return _u
}

// SetNillableMikrotikUsername sets the "mikrotik_username" field if the given value is not nil.
func (_u *AppConfigUpdateOne) SetNillableMikrotikUsername(v *string) *AppConfigUpdateOne {
	if v != nil {
		_u.SetMikrotikUsername(*v)
	}
	return _u
}

// SetMikrotikPassword sets the "mikrotik_password" field.
func (_u *AppConfigUpdateOne) SetMikrotikPassword(v string) *AppConfigUpdateOne {
	_u.mutation.SetMikrotikPassword(v)
	return _u
}

// SetNillableMikrotikPassword sets the "mikrotik_password" field if the given value is not nil.
func (_u *AppConfigUpdateOne) SetNillableMikrotikPassword(v *string) *AppConfigUpdateOne {
	if v != nil {
		_u.SetMikrotikPassword(*v)
	}
	return _u
}

// SetOauthIssuer sets the "oauth_issuer" field.
func (_u *AppConfigUpdateOne) SetOauthIssuer(v string) *AppConfigUpdateOne {
	_u.mutation.SetOauthIssuer(v)
	return _u
}

// SetNillableOauthIssuer sets the "oauth_issuer" field if the given value is not nil.
func (_u *AppConfigUpdateOne) SetNillableOauthIssuer(v *string) *AppConfigUpdateOne {
	if v != nil {
		_u.SetOauthIssuer(*v)
	}
	return _u
}

// SetOauthAudience sets the "oauth_audience" field.
func (_u *AppConfigUpdateOne) SetOauthAudience(v string) *AppConfigUpdateOne {
	_u.mutation.SetOauthAudience(v)
	return _u
}

// SetNillableOauthAudience sets the "oauth_audience" field if the given value is not nil.
func (_u *AppConfigUpdateOne) SetNillableOauthAudience(v *string) *AppConfigUpdateOne {
	if v != nil {
		_u.SetOauthAudience(*v)
	}
	return _u
}

// SetVlanScope sets the "vlan_scope" field.
func (_u *AppConfigUpdateOne) SetVlanScope(v string) *AppConfigUpdateOne {
	_u.mutation.SetVlanScope(v)
	return _u
}

// SetNillableVlanScope sets the "vlan_scope" field if the given value is not nil.
func (_u *AppConfigUpdateOne) SetNillableVlanScope(v *string) *AppConfigUpdateOne {
	if v != nil {
		_u.SetVlanScope(*v)
	}
	return _u
}

// SetEnableAuthentication sets the "enable_authentication" field.
func (_u *AppConfigUpdateOne) SetEnableAuthentication(v bool) *AppConfigUpdateOne {
	_u.mutation.SetEnableAuthentication(v)
	return _u
}

// SetNillableEnableAuthentication sets the "enable_authentication" field if the given value is not nil.
func (_u *AppConfigUpdateOne) SetNillableEnableAuthentication(v *bool) *AppConfigUpdateOne {
	if v != nil {
		_u.SetEnableAuthentication(*v)
	}
	return _u
}

// Mutation returns the AppConfigMutation object of the builder.
func (_u *AppConfigUpdateOne) Mutation() *AppConfigMutation {
	return _u.mutation
}

// Where appends a list predicates to the AppConfigUpdate builder.
func (_u *AppConfigUpdateOne) Where(ps ...predicate.AppConfig) *AppConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AppConfigUpdateOne) Select(field string, fields ...string) *AppConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AppConfig entity.
func (_u *AppConfigUpdateOne) Save(ctx context.Context) (*AppConfig, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AppConfigUpdateOne) SaveX(ctx context.Context) *AppConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AppConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AppConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AppConfigUpdateOne) sqlSave(ctx context.Context) (_node *AppConfig, err error) {
	_spec := sqlgraph.NewUpdateSpec(appconfig.Table, appconfig.Columns, sqlgraph.NewFieldSpec(appconfig.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AppConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, appconfig.FieldID)
		for _, f := range fields {
			if !appconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != appconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MikrotikAddress(); ok {
		_spec.SetField(appconfig.FieldMikrotikAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.MikrotikUsername(); ok {
		_spec.SetField(appconfig.FieldMikrotikUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.MikrotikPassword(); ok {
		_spec.SetField(appconfig.FieldMikrotikPassword, field.TypeString, value)
	}
	if value, ok := _u.mutation.OauthIssuer(); ok {
		_spec.SetField(appconfig.FieldOauthIssuer, field.TypeString, value)
	}
	if value, ok := _u.mutation.OauthAudience(); ok {
		_spec.SetField(appconfig.FieldOauthAudience, field.TypeString, value)
	}
	if value, ok := _u.mutation.VlanScope(); ok {
		_spec.SetField(appconfig.FieldVlanScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.EnableAuthentication(); ok {
		_spec.SetField(appconfig.FieldEnableAuthentication, field.TypeBool, value)
	}
	_node = &AppConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{appconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
