// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-mikrotik-vlan-switcher/ent/appconfig"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AppConfigCreate is the builder for creating a AppConfig entity.
type AppConfigCreate struct {
	config
	mutation *AppConfigMutation
	hooks    []Hook
}

// SetMikrotikAddress sets the "mikrotik_address" field.
func (_c *AppConfigCreate) SetMikrotikAddress(v string) *AppConfigCreate {
	_c.mutation.SetMikrotikAddress(v)
	return _c
}

// SetMikrotikUsername sets the "mikrotik_username" field.
func (_c *AppConfigCreate) SetMikrotikUsername(v string) *AppConfigCreate {
	_c.mutation.SetMikrotikUsername(v)
	return _c
}

// SetMikrotikPassword sets the "mikrotik_password" field.
func (_c *AppConfigCreate) SetMikrotikPassword(v string) *AppConfigCreate {
	_c.mutation.SetMikrotikPassword(v)
	return _c
}

// SetOauthIssuer sets the "oauth_issuer" field.
func (_c *AppConfigCreate) SetOauthIssuer(v string) *AppConfigCreate {
	_c.mutation.SetOauthIssuer(v)
	return _c
}

// SetOauthAudience sets the "oauth_audience" field.
func (_c *AppConfigCreate) SetOauthAudience(v string) *AppConfigCreate {
	_c.mutation.SetOauthAudience(v)
	return _c
}

// SetVlanScope sets the "vlan_scope" field.
func (_c *AppConfigCreate) SetVlanScope(v string) *AppConfigCreate {
	_c.mutation.SetVlanScope(v)
	return _c
}

// SetEnableAuthentication sets the "enable_authentication" field.
func (_c *AppConfigCreate) SetEnableAuthentication(v bool) *AppConfigCreate {
	_c.mutation.SetEnableAuthentication(v)
	return _c
}

// SetNillableEnableAuthentication sets the "enable_authentication" field if the given value is not nil.
func (_c *AppConfigCreate) SetNillableEnableAuthentication(v *bool) *AppConfigCreate {
	if v != nil {
		_c.SetEnableAuthentication(*v)
	}
	return _c
}

// Mutation returns the AppConfigMutation object of the builder.
func (_c *AppConfigCreate) Mutation() *AppConfigMutation {
	return _c.mutation
}

// Save creates the AppConfig in the database.
func (_c *AppConfigCreate) Save(ctx context.Context) (*AppConfig, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AppConfigCreate) SaveX(ctx context.Context) *AppConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AppConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AppConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AppConfigCreate) defaults() {
	if _, ok := _c.mutation.EnableAuthentication(); !ok {
		v := appconfig.DefaultEnableAuthentication
		_c.mutation.SetEnableAuthentication(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AppConfigCreate) check() error {
	if _, ok := _c.mutation.MikrotikAddress(); !ok {
		return &ValidationError{Name: "mikrotik_address", err: errors.New(`ent: missing required field "AppConfig.mikrotik_address"`)}
	}
	if _, ok := _c.mutation.MikrotikUsername(); !ok {
		return &ValidationError{Name: "mikrotik_username", err: errors.New(`ent: missing required field "AppConfig.mikrotik_username"`)}
	}
	if _, ok := _c.mutation.MikrotikPassword(); !ok {
		return &ValidationError{Name: "mikrotik_password", err: errors.New(`ent: missing required field "AppConfig.mikrotik_password"`)}
	}
	if _, ok := _c.mutation.OauthIssuer(); !ok {
		return &ValidationError{Name: "oauth_issuer", err: errors.New(`ent: missing required field "AppConfig.oauth_issuer"`)}
	}
	if _, ok := _c.mutation.OauthAudience(); !ok {
		return &ValidationError{Name: "oauth_audience", err: errors.New(`ent: missing required field "AppConfig.oauth_audience"`)}
	}
	if _, ok := _c.mutation.VlanScope(); !ok {
		return &ValidationError{Name: "vlan_scope", err: errors.New(`ent: missing required field "AppConfig.vlan_scope"`)}
	}
	if _, ok := _c.mutation.EnableAuthentication(); !ok {
		return &ValidationError{Name: "enable_authentication", err: errors.New(`ent: missing required field "AppConfig.enable_authentication"`)}
	}
	return nil
}

func (_c *AppConfigCreate) sqlSave(ctx context.Context) (*AppConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AppConfigCreate) createSpec() (*AppConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &AppConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(appconfig.Table, sqlgraph.NewFieldSpec(appconfig.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.MikrotikAddress(); ok {
		_spec.SetField(appconfig.FieldMikrotikAddress, field.TypeString, value)
		_node.MikrotikAddress = value
	}
	if value, ok := _c.mutation.MikrotikUsername(); ok {
		_spec.SetField(appconfig.FieldMikrotikUsername, field.TypeString, value)
		_node.MikrotikUsername = value
	}
	if value, ok := _c.mutation.MikrotikPassword(); ok {
		_spec.SetField(appconfig.FieldMikrotikPassword, field.TypeString, value)
		_node.MikrotikPassword = value
	}
	if value, ok := _c.mutation.OauthIssuer(); ok {
		_spec.SetField(appconfig.FieldOauthIssuer, field.TypeString, value)
		_node.OauthIssuer = value
	}
	if value, ok := _c.mutation.OauthAudience(); ok {
		_spec.SetField(appconfig.FieldOauthAudience, field.TypeString, value)
		_node.OauthAudience = value
	}
	if value, ok := _c.mutation.VlanScope(); ok {
		_spec.SetField(appconfig.FieldVlanScope, field.TypeString, value)
		_node.VlanScope = value
	}
	if value, ok := _c.mutation.EnableAuthentication(); ok {
		_spec.SetField(appconfig.FieldEnableAuthentication, field.TypeBool, value)
		_node.EnableAuthentication = value
	}
	return _node, _spec
}

// AppConfigCreateBulk is the builder for creating many AppConfig entities in bulk.
type AppConfigCreateBulk struct {
	config
	err      error
	builders []*AppConfigCreate
}

// Save creates the AppConfig entities in the database.
func (_c *AppConfigCreateBulk) Save(ctx context.Context) ([]*AppConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AppConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AppConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AppConfigCreateBulk) SaveX(ctx context.Context) []*AppConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AppConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AppConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
