// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-mikrotik-vlan-switcher/ent/interfacevlanstate"
	"go-mikrotik-vlan-switcher/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// InterfaceVlanStateUpdate is the builder for updating InterfaceVlanState entities.
type InterfaceVlanStateUpdate struct {
	config
	hooks    []Hook
	mutation *InterfaceVlanStateMutation
}

// Where appends a list predicates to the InterfaceVlanStateUpdate builder.
func (_u *InterfaceVlanStateUpdate) Where(ps ...predicate.InterfaceVlanState) *InterfaceVlanStateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetInterface sets the "interface" field.
func (_u *InterfaceVlanStateUpdate) SetInterface(v string) *InterfaceVlanStateUpdate {
	_u.mutation.SetInterface(v)
	return _u
}

// SetNillableInterface sets the "interface" field if the given value is not nil.
func (_u *InterfaceVlanStateUpdate) SetNillableInterface(v *string) *InterfaceVlanStateUpdate {
	if v != nil {
		_u.SetInterface(*v)
	}
	return _u
}

// SetCurrentList sets the "current_list" field.
func (_u *InterfaceVlanStateUpdate) SetCurrentList(v string) *InterfaceVlanStateUpdate {
	_u.mutation.SetCurrentList(v)
	return _u
}

// SetNillableCurrentList sets the "current_list" field if the given value is not nil.
func (_u *InterfaceVlanStateUpdate) SetNillableCurrentList(v *string) *InterfaceVlanStateUpdate {
	if v != nil {
		_u.SetCurrentList(*v)
	}
	return _u
}

// SetCurrentVlanID sets the "current_vlan_id" field.
func (_u *InterfaceVlanStateUpdate) SetCurrentVlanID(v int) *InterfaceVlanStateUpdate {
	_u.mutation.ResetCurrentVlanID()
	_u.mutation.SetCurrentVlanID(v)
	return _u
}

// SetNillableCurrentVlanID sets the "current_vlan_id" field if the given value is not nil.
func (_u *InterfaceVlanStateUpdate) SetNillableCurrentVlanID(v *int) *InterfaceVlanStateUpdate {
	if v != nil {
		_u.SetCurrentVlanID(*v)
	}
	return _u
}

// AddCurrentVlanID adds value to the "current_vlan_id" field.
func (_u *InterfaceVlanStateUpdate) AddCurrentVlanID(v int) *InterfaceVlanStateUpdate {
	_u.mutation.AddCurrentVlanID(v)
	return _u
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_u *InterfaceVlanStateUpdate) SetLastSyncedAt(v time.Time) *InterfaceVlanStateUpdate {
	_u.mutation.SetLastSyncedAt(v)
	return _u
}

// Mutation returns the InterfaceVlanStateMutation object of the builder.
func (_u *InterfaceVlanStateUpdate) Mutation() *InterfaceVlanStateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InterfaceVlanStateUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InterfaceVlanStateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InterfaceVlanStateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InterfaceVlanStateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InterfaceVlanStateUpdate) defaults() {
	if _, ok := _u.mutation.LastSyncedAt(); !ok {
		v := interfacevlanstate.UpdateDefaultLastSyncedAt()
		_u.mutation.SetLastSyncedAt(v)
	}
}

func (_u *InterfaceVlanStateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(interfacevlanstate.Table, interfacevlanstate.Columns, sqlgraph.NewFieldSpec(interfacevlanstate.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Interface(); ok {
		_spec.SetField(interfacevlanstate.FieldInterface, field.TypeString, value)
	}
	if value, ok := _u.mutation.CurrentList(); ok {
		_spec.SetField(interfacevlanstate.FieldCurrentList, field.TypeString, value)
	}
	if value, ok := _u.mutation.CurrentVlanID(); ok {
		_spec.SetField(interfacevlanstate.FieldCurrentVlanID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCurrentVlanID(); ok {
		_spec.AddField(interfacevlanstate.FieldCurrentVlanID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastSyncedAt(); ok {
		_spec.SetField(interfacevlanstate.FieldLastSyncedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{interfacevlanstate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InterfaceVlanStateUpdateOne is the builder for updating a single InterfaceVlanState entity.
type InterfaceVlanStateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InterfaceVlanStateMutation
}

// SetInterface sets the "interface" field.
func (_u *InterfaceVlanStateUpdateOne) SetInterface(v string) *InterfaceVlanStateUpdateOne {
	_u.mutation.SetInterface(v)
	return _u
}

// SetNillableInterface sets the "interface" field if the given value is not nil.
func (_u *InterfaceVlanStateUpdateOne) SetNillableInterface(v *string) *InterfaceVlanStateUpdateOne {
	if v != nil {
		_u.SetInterface(*v)
	}
	return _u
}

// SetCurrentList sets the "current_list" field.
func (_u *InterfaceVlanStateUpdateOne) SetCurrentList(v string) *InterfaceVlanStateUpdateOne {
	_u.mutation.SetCurrentList(v)
	return _u
}

// SetNillableCurrentList sets the "current_list" field if the given value is not nil.
func (_u *InterfaceVlanStateUpdateOne) SetNillableCurrentList(v *string) *InterfaceVlanStateUpdateOne {
	if v != nil {
		_u.SetCurrentList(*v)
	}
	return _u
}

// SetCurrentVlanID sets the "current_vlan_id" field.
func (_u *InterfaceVlanStateUpdateOne) SetCurrentVlanID(v int) *InterfaceVlanStateUpdateOne {
	_u.mutation.ResetCurrentVlanID()
	_u.mutation.SetCurrentVlanID(v)
	return _u
}

// SetNillableCurrentVlanID sets the "current_vlan_id" field if the given value is not nil.
func (_u *InterfaceVlanStateUpdateOne) SetNillableCurrentVlanID(v *int) *InterfaceVlanStateUpdateOne {
	if v != nil {
		_u.SetCurrentVlanID(*v)
	}
	return _u
}

// AddCurrentVlanID adds value to the "current_vlan_id" field.
func (_u *InterfaceVlanStateUpdateOne) AddCurrentVlanID(v int) *InterfaceVlanStateUpdateOne {
	_u.mutation.AddCurrentVlanID(v)
	return _u
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_u *InterfaceVlanStateUpdateOne) SetLastSyncedAt(v time.Time) *InterfaceVlanStateUpdateOne {
	_u.mutation.SetLastSyncedAt(v)
	return _u
}

// Mutation returns the InterfaceVlanStateMutation object of the builder.
func (_u *InterfaceVlanStateUpdateOne) Mutation() *InterfaceVlanStateMutation {
	return _u.mutation
}

// Where appends a list predicates to the InterfaceVlanStateUpdate builder.
func (_u *InterfaceVlanStateUpdateOne) Where(ps ...predicate.InterfaceVlanState) *InterfaceVlanStateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InterfaceVlanStateUpdateOne) Select(field string, fields ...string) *InterfaceVlanStateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated InterfaceVlanState entity.
func (_u *InterfaceVlanStateUpdateOne) Save(ctx context.Context) (*InterfaceVlanState, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InterfaceVlanStateUpdateOne) SaveX(ctx context.Context) *InterfaceVlanState {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InterfaceVlanStateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InterfaceVlanStateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InterfaceVlanStateUpdateOne) defaults() {
	if _, ok := _u.mutation.LastSyncedAt(); !ok {
		v := interfacevlanstate.UpdateDefaultLastSyncedAt()
		_u.mutation.SetLastSyncedAt(v)
	}
}

func (_u *InterfaceVlanStateUpdateOne) sqlSave(ctx context.Context) (_node *InterfaceVlanState, err error) {
	_spec := sqlgraph.NewUpdateSpec(interfacevlanstate.Table, interfacevlanstate.Columns, sqlgraph.NewFieldSpec(interfacevlanstate.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InterfaceVlanState.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, interfacevlanstate.FieldID)
		for _, f := range fields {
			if !interfacevlanstate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != interfacevlanstate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Interface(); ok {
		_spec.SetField(interfacevlanstate.FieldInterface, field.TypeString, value)
	}
	if value, ok := _u.mutation.CurrentList(); ok {
		_spec.SetField(interfacevlanstate.FieldCurrentList, field.TypeString, value)
	}
	if value, ok := _u.mutation.CurrentVlanID(); ok {
		_spec.SetField(interfacevlanstate.FieldCurrentVlanID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCurrentVlanID(); ok {
		_spec.AddField(interfacevlanstate.FieldCurrentVlanID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastSyncedAt(); ok {
		_spec.SetField(interfacevlanstate.FieldLastSyncedAt, field.TypeTime, value)
	}
	_node = &InterfaceVlanState{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{interfacevlanstate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
