// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-mikrotik-vlan-switcher/ent/interfacevlanstate"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// InterfaceVlanStateCreate is the builder for creating a InterfaceVlanState entity.
type InterfaceVlanStateCreate struct {
	config
	mutation *InterfaceVlanStateMutation
	hooks    []Hook
}

// SetInterface sets the "interface" field.
func (_c *InterfaceVlanStateCreate) SetInterface(v string) *InterfaceVlanStateCreate {
	_c.mutation.SetInterface(v)
	return _c
}

// SetCurrentList sets the "current_list" field.
func (_c *InterfaceVlanStateCreate) SetCurrentList(v string) *InterfaceVlanStateCreate {
	_c.mutation.SetCurrentList(v)
	return _c
}

// SetCurrentVlanID sets the "current_vlan_id" field.
func (_c *InterfaceVlanStateCreate) SetCurrentVlanID(v int) *InterfaceVlanStateCreate {
	_c.mutation.SetCurrentVlanID(v)
	return _c
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_c *InterfaceVlanStateCreate) SetLastSyncedAt(v time.Time) *InterfaceVlanStateCreate {
	_c.mutation.SetLastSyncedAt(v)
	return _c
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_c *InterfaceVlanStateCreate) SetNillableLastSyncedAt(v *time.Time) *InterfaceVlanStateCreate {
	if v != nil {
		_c.SetLastSyncedAt(*v)
	}
	return _c
}

// Mutation returns the InterfaceVlanStateMutation object of the builder.
func (_c *InterfaceVlanStateCreate) Mutation() *InterfaceVlanStateMutation {
	return _c.mutation
}

// Save creates the InterfaceVlanState in the database.
func (_c *InterfaceVlanStateCreate) Save(ctx context.Context) (*InterfaceVlanState, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InterfaceVlanStateCreate) SaveX(ctx context.Context) *InterfaceVlanState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InterfaceVlanStateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InterfaceVlanStateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InterfaceVlanStateCreate) defaults() {
	if _, ok := _c.mutation.LastSyncedAt(); !ok {
		v := interfacevlanstate.DefaultLastSyncedAt()
		_c.mutation.SetLastSyncedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InterfaceVlanStateCreate) check() error {
	if _, ok := _c.mutation.Interface(); !ok {
		return &ValidationError{Name: "interface", err: errors.New(`ent: missing required field "InterfaceVlanState.interface"`)}
	}
	if _, ok := _c.mutation.CurrentList(); !ok {
		return &ValidationError{Name: "current_list", err: errors.New(`ent: missing required field "InterfaceVlanState.current_list"`)}
	}
	if _, ok := _c.mutation.CurrentVlanID(); !ok {
		return &ValidationError{Name: "current_vlan_id", err: errors.New(`ent: missing required field "InterfaceVlanState.current_vlan_id"`)}
	}
	if _, ok := _c.mutation.LastSyncedAt(); !ok {
		return &ValidationError{Name: "last_synced_at", err: errors.New(`ent: missing required field "InterfaceVlanState.last_synced_at"`)}
	}
	return nil
}

func (_c *InterfaceVlanStateCreate) sqlSave(ctx context.Context) (*InterfaceVlanState, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InterfaceVlanStateCreate) createSpec() (*InterfaceVlanState, *sqlgraph.CreateSpec) {
	var (
		_node = &InterfaceVlanState{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(interfacevlanstate.Table, sqlgraph.NewFieldSpec(interfacevlanstate.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Interface(); ok {
		_spec.SetField(interfacevlanstate.FieldInterface, field.TypeString, value)
		_node.Interface = value
	}
	if value, ok := _c.mutation.CurrentList(); ok {
		_spec.SetField(interfacevlanstate.FieldCurrentList, field.TypeString, value)
		_node.CurrentList = value
	}
	if value, ok := _c.mutation.CurrentVlanID(); ok {
		_spec.SetField(interfacevlanstate.FieldCurrentVlanID, field.TypeInt, value)
		_node.CurrentVlanID = value
	}
	if value, ok := _c.mutation.LastSyncedAt(); ok {
		_spec.SetField(interfacevlanstate.FieldLastSyncedAt, field.TypeTime, value)
		_node.LastSyncedAt = value
	}
	return _node, _spec
}

// InterfaceVlanStateCreateBulk is the builder for creating many InterfaceVlanState entities in bulk.
type InterfaceVlanStateCreateBulk struct {
	config
	err      error
	builders []*InterfaceVlanStateCreate
}

// Save creates the InterfaceVlanState entities in the database.
func (_c *InterfaceVlanStateCreateBulk) Save(ctx context.Context) ([]*InterfaceVlanState, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InterfaceVlanState, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InterfaceVlanStateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InterfaceVlanStateCreateBulk) SaveX(ctx context.Context) []*InterfaceVlanState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InterfaceVlanStateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InterfaceVlanStateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
