// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"go-mikrotik-vlan-switcher/ent/interfacevlanstate"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// InterfaceVlanState is the model entity for the InterfaceVlanState schema.
type InterfaceVlanState struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Interface holds the value of the "interface" field.
	Interface string `json:"interface,omitempty"`
	// CurrentList holds the value of the "current_list" field.
	CurrentList string `json:"current_list,omitempty"`
	// CurrentVlanID holds the value of the "current_vlan_id" field.
	CurrentVlanID int `json:"current_vlan_id,omitempty"`
	// LastSyncedAt holds the value of the "last_synced_at" field.
	LastSyncedAt time.Time `json:"last_synced_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InterfaceVlanState) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case interfacevlanstate.FieldID, interfacevlanstate.FieldCurrentVlanID:
			values[i] = new(sql.NullInt64)
		case interfacevlanstate.FieldInterface, interfacevlanstate.FieldCurrentList:
			values[i] = new(sql.NullString)
		case interfacevlanstate.FieldLastSyncedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InterfaceVlanState fields.
func (_m *InterfaceVlanState) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case interfacevlanstate.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case interfacevlanstate.FieldInterface:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field interface", values[i])
			} else if value.Valid {
				_m.Interface = value.String
			}
		case interfacevlanstate.FieldCurrentList:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field current_list", values[i])
			} else if value.Valid {
				_m.CurrentList = value.String
			}
		case interfacevlanstate.FieldCurrentVlanID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field current_vlan_id", values[i])
			} else if value.Valid {
				_m.CurrentVlanID = int(value.Int64)
			}
		case interfacevlanstate.FieldLastSyncedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_synced_at", values[i])
			} else if value.Valid {
				_m.LastSyncedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the InterfaceVlanState.
// This includes values selected through modifiers, order, etc.
func (_m *InterfaceVlanState) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this InterfaceVlanState.
// Note that you need to call InterfaceVlanState.Unwrap() before calling this method if this InterfaceVlanState
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *InterfaceVlanState) Update() *InterfaceVlanStateUpdateOne {
	return NewInterfaceVlanStateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the InterfaceVlanState entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *InterfaceVlanState) Unwrap() *InterfaceVlanState {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: InterfaceVlanState is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *InterfaceVlanState) String() string {
	var builder strings.Builder
	builder.WriteString("InterfaceVlanState(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("interface=")
	builder.WriteString(_m.Interface)
	builder.WriteString(", ")
	builder.WriteString("current_list=")
	builder.WriteString(_m.CurrentList)
	builder.WriteString(", ")
	builder.WriteString("current_vlan_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CurrentVlanID))
	builder.WriteString(", ")
	builder.WriteString("last_synced_at=")
	builder.WriteString(_m.LastSyncedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// InterfaceVlanStates is a parsable slice of InterfaceVlanState.
type InterfaceVlanStates []*InterfaceVlanState
