// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"go-mikrotik-vlan-switcher/ent/interfacevlanstate"
	"go-mikrotik-vlan-switcher/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// InterfaceVlanStateDelete is the builder for deleting a InterfaceVlanState entity.
type InterfaceVlanStateDelete struct {
	config
	hooks    []Hook
	mutation *InterfaceVlanStateMutation
}

// Where appends a list predicates to the InterfaceVlanStateDelete builder.
func (_d *InterfaceVlanStateDelete) Where(ps ...predicate.InterfaceVlanState) *InterfaceVlanStateDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *InterfaceVlanStateDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *InterfaceVlanStateDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *InterfaceVlanStateDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(interfacevlanstate.Table, sqlgraph.NewFieldSpec(interfacevlanstate.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// InterfaceVlanStateDeleteOne is the builder for deleting a single InterfaceVlanState entity.
type InterfaceVlanStateDeleteOne struct {
	_d *InterfaceVlanStateDelete
}

// Where appends a list predicates to the InterfaceVlanStateDelete builder.
func (_d *InterfaceVlanStateDeleteOne) Where(ps ...predicate.InterfaceVlanState) *InterfaceVlanStateDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *InterfaceVlanStateDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{interfacevlanstate.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *InterfaceVlanStateDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
