// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-mikrotik-vlan-switcher/ent/appconfig"
	"go-mikrotik-vlan-switcher/ent/interfacevlanstate"
	"go-mikrotik-vlan-switcher/ent/predicate"
	"go-mikrotik-vlan-switcher/ent/requestcmd"
	"go-mikrotik-vlan-switcher/ent/requestlog"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeAppConfig          = "AppConfig"
	TypeInterfaceVlanState = "InterfaceVlanState"
	TypeRequestCmd         = "RequestCmd"
	TypeRequestLog         = "RequestLog"
)

// AppConfigMutation represents an operation that mutates the AppConfig nodes in the graph.
type AppConfigMutation struct {
	config
	op                    Op
	typ                   string
	id                    *int
	mikrotik_address      *string
	mikrotik_username     *string
	mikrotik_password     *string
	oauth_issuer          *string
	oauth_audience        *string
	vlan_scope            *string
	enable_authentication *bool
	clearedFields         map[string]struct{}
	done                  bool
	oldValue              func(context.Context) (*AppConfig, error)
	predicates            []predicate.AppConfig
}

var _ ent.Mutation = (*AppConfigMutation)(nil)

// appconfigOption allows management of the mutation configuration using functional options.
type appconfigOption func(*AppConfigMutation)

// newAppConfigMutation creates new mutation for the AppConfig entity.
func newAppConfigMutation(c config, op Op, opts ...appconfigOption) *AppConfigMutation {
	m := &AppConfigMutation{
		config:        c,
		op:            op,
		typ:           TypeAppConfig,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withAppConfigID sets the ID field of the mutation.
func withAppConfigID(id int) appconfigOption {
	return func(m *AppConfigMutation) {
		var (
			err   error
			once  sync.Once
			value *AppConfig
		)
		m.oldValue = func(ctx context.Context) (*AppConfig, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().AppConfig.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withAppConfig sets the old AppConfig of the mutation.
func withAppConfig(node *AppConfig) appconfigOption {
	return func(m *AppConfigMutation) {
		m.oldValue = func(context.Context) (*AppConfig, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m AppConfigMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m AppConfigMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *AppConfigMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *AppConfigMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().AppConfig.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetMikrotikAddress sets the "mikrotik_address" field.
func (m *AppConfigMutation) SetMikrotikAddress(s string) {
	m.mikrotik_address = &s
}

// MikrotikAddress returns the value of the "mikrotik_address" field in the mutation.
func (m *AppConfigMutation) MikrotikAddress() (r string, exists bool) {
	v := m.mikrotik_address
	if v == nil {
		return
	}
	return *v, true
}

// OldMikrotikAddress returns the old "mikrotik_address" field's value of the AppConfig entity.
// If the AppConfig object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AppConfigMutation) OldMikrotikAddress(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMikrotikAddress is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMikrotikAddress requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMikrotikAddress: %w", err)
	}
	return oldValue.MikrotikAddress, nil
}

// ResetMikrotikAddress resets all changes to the "mikrotik_address" field.
func (m *AppConfigMutation) ResetMikrotikAddress() {
	m.mikrotik_address = nil
}

// SetMikrotikUsername sets the "mikrotik_username" field.
func (m *AppConfigMutation) SetMikrotikUsername(s string) {
	m.mikrotik_username = &s
}

// MikrotikUsername returns the value of the "mikrotik_username" field in the mutation.
func (m *AppConfigMutation) MikrotikUsername() (r string, exists bool) {
	v := m.mikrotik_username
	if v == nil {
		return
	}
	return *v, true
}

// OldMikrotikUsername returns the old "mikrotik_username" field's value of the AppConfig entity.
// If the AppConfig object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AppConfigMutation) OldMikrotikUsername(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMikrotikUsername is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMikrotikUsername requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMikrotikUsername: %w", err)
	}
	return oldValue.MikrotikUsername, nil
}

// ResetMikrotikUsername resets all changes to the "mikrotik_username" field.
func (m *AppConfigMutation) ResetMikrotikUsername() {
	m.mikrotik_username = nil
}

// SetMikrotikPassword sets the "mikrotik_password" field.
func (m *AppConfigMutation) SetMikrotikPassword(s string) {
	m.mikrotik_password = &s
}

// MikrotikPassword returns the value of the "mikrotik_password" field in the mutation.
func (m *AppConfigMutation) MikrotikPassword() (r string, exists bool) {
	v := m.mikrotik_password
	if v == nil {
		return
	}
	return *v, true
}

// OldMikrotikPassword returns the old "mikrotik_password" field's value of the AppConfig entity.
// If the AppConfig object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AppConfigMutation) OldMikrotikPassword(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMikrotikPassword is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMikrotikPassword requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMikrotikPassword: %w", err)
	}
	return oldValue.MikrotikPassword, nil
}

// ResetMikrotikPassword resets all changes to the "mikrotik_password" field.
func (m *AppConfigMutation) ResetMikrotikPassword() {
	m.mikrotik_password = nil
}

// SetOauthIssuer sets the "oauth_issuer" field.
func (m *AppConfigMutation) SetOauthIssuer(s string) {
	m.oauth_issuer = &s
}

// OauthIssuer returns the value of the "oauth_issuer" field in the mutation.
func (m *AppConfigMutation) OauthIssuer() (r string, exists bool) {
	v := m.oauth_issuer
	if v == nil {
		return
	}
	return *v, true
}

// OldOauthIssuer returns the old "oauth_issuer" field's value of the AppConfig entity.
// If the AppConfig object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AppConfigMutation) OldOauthIssuer(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOauthIssuer is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOauthIssuer requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOauthIssuer: %w", err)
	}
	return oldValue.OauthIssuer, nil
}

// ResetOauthIssuer resets all changes to the "oauth_issuer" field.
func (m *AppConfigMutation) ResetOauthIssuer() {
	m.oauth_issuer = nil
}

// SetOauthAudience sets the "oauth_audience" field.
func (m *AppConfigMutation) SetOauthAudience(s string) {
	m.oauth_audience = &s
}

// OauthAudience returns the value of the "oauth_audience" field in the mutation.
func (m *AppConfigMutation) OauthAudience() (r string, exists bool) {
	v := m.oauth_audience
	if v == nil {
		return
	}
	return *v, true
}

// OldOauthAudience returns the old "oauth_audience" field's value of the AppConfig entity.
// If the AppConfig object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AppConfigMutation) OldOauthAudience(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOauthAudience is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOauthAudience requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOauthAudience: %w", err)
	}
	return oldValue.OauthAudience, nil
}

// ResetOauthAudience resets all changes to the "oauth_audience" field.
func (m *AppConfigMutation) ResetOauthAudience() {
	m.oauth_audience = nil
}

// SetVlanScope sets the "vlan_scope" field.
func (m *AppConfigMutation) SetVlanScope(s string) {
	m.vlan_scope = &s
}

// VlanScope returns the value of the "vlan_scope" field in the mutation.
func (m *AppConfigMutation) VlanScope() (r string, exists bool) {
	v := m.vlan_scope
	if v == nil {
		return
	}
	return *v, true
}

// OldVlanScope returns the old "vlan_scope" field's value of the AppConfig entity.
// If the AppConfig object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AppConfigMutation) OldVlanScope(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldVlanScope is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldVlanScope requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldVlanScope: %w", err)
	}
	return oldValue.VlanScope, nil
}

// ResetVlanScope resets all changes to the "vlan_scope" field.
func (m *AppConfigMutation) ResetVlanScope() {
	m.vlan_scope = nil
}

// SetEnableAuthentication sets the "enable_authentication" field.
func (m *AppConfigMutation) SetEnableAuthentication(b bool) {
	m.enable_authentication = &b
}

// EnableAuthentication returns the value of the "enable_authentication" field in the mutation.
func (m *AppConfigMutation) EnableAuthentication() (r bool, exists bool) {
	v := m.enable_authentication
	if v == nil {
		return
	}
	return *v, true
}

// OldEnableAuthentication returns the old "enable_authentication" field's value of the AppConfig entity.
// If the AppConfig object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AppConfigMutation) OldEnableAuthentication(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEnableAuthentication is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEnableAuthentication requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEnableAuthentication: %w", err)
	}
	return oldValue.EnableAuthentication, nil
}

// ResetEnableAuthentication resets all changes to the "enable_authentication" field.
func (m *AppConfigMutation) ResetEnableAuthentication() {
	m.enable_authentication = nil
}

// Where appends a list predicates to the AppConfigMutation builder.
func (m *AppConfigMutation) Where(ps ...predicate.AppConfig) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the AppConfigMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *AppConfigMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.AppConfig, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *AppConfigMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *AppConfigMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (AppConfig).
func (m *AppConfigMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *AppConfigMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.mikrotik_address != nil {
		fields = append(fields, appconfig.FieldMikrotikAddress)
	}
	if m.mikrotik_username != nil {
		fields = append(fields, appconfig.FieldMikrotikUsername)
	}
	if m.mikrotik_password != nil {
		fields = append(fields, appconfig.FieldMikrotikPassword)
	}
	if m.oauth_issuer != nil {
		fields = append(fields, appconfig.FieldOauthIssuer)
	}
	if m.oauth_audience != nil {
		fields = append(fields, appconfig.FieldOauthAudience)
	}
	if m.vlan_scope != nil {
		fields = append(fields, appconfig.FieldVlanScope)
	}
	if m.enable_authentication != nil {
		fields = append(fields, appconfig.FieldEnableAuthentication)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *AppConfigMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case appconfig.FieldMikrotikAddress:
		return m.MikrotikAddress()
	case appconfig.FieldMikrotikUsername:
		return m.MikrotikUsername()
	case appconfig.FieldMikrotikPassword:
		return m.MikrotikPassword()
	case appconfig.FieldOauthIssuer:
		return m.OauthIssuer()
	case appconfig.FieldOauthAudience:
		return m.OauthAudience()
	case appconfig.FieldVlanScope:
		return m.VlanScope()
	case appconfig.FieldEnableAuthentication:
		return m.EnableAuthentication()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *AppConfigMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case appconfig.FieldMikrotikAddress:
		return m.OldMikrotikAddress(ctx)
	case appconfig.FieldMikrotikUsername:
		return m.OldMikrotikUsername(ctx)
	case appconfig.FieldMikrotikPassword:
		return m.OldMikrotikPassword(ctx)
	case appconfig.FieldOauthIssuer:
		return m.OldOauthIssuer(ctx)
	case appconfig.FieldOauthAudience:
		return m.OldOauthAudience(ctx)
	case appconfig.FieldVlanScope:
		return m.OldVlanScope(ctx)
	case appconfig.FieldEnableAuthentication:
		return m.OldEnableAuthentication(ctx)
	}
	return nil, fmt.Errorf("unknown AppConfig field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AppConfigMutation) SetField(name string, value ent.Value) error {
	switch name {
	case appconfig.FieldMikrotikAddress:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMikrotikAddress(v)
		return nil
	case appconfig.FieldMikrotikUsername:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMikrotikUsername(v)
		return nil
	case appconfig.FieldMikrotikPassword:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMikrotikPassword(v)
		return nil
	case appconfig.FieldOauthIssuer:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOauthIssuer(v)
		return nil
	case appconfig.FieldOauthAudience:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOauthAudience(v)
		return nil
	case appconfig.FieldVlanScope:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetVlanScope(v)
		return nil
	case appconfig.FieldEnableAuthentication:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEnableAuthentication(v)
		return nil
	}
	return fmt.Errorf("unknown AppConfig field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *AppConfigMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *AppConfigMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AppConfigMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown AppConfig numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *AppConfigMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *AppConfigMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *AppConfigMutation) ClearField(name string) error {
	return fmt.Errorf("unknown AppConfig nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *AppConfigMutation) ResetField(name string) error {
	switch name {
	case appconfig.FieldMikrotikAddress:
		m.ResetMikrotikAddress()
		return nil
	case appconfig.FieldMikrotikUsername:
		m.ResetMikrotikUsername()
		return nil
	case appconfig.FieldMikrotikPassword:
		m.ResetMikrotikPassword()
		return nil
	case appconfig.FieldOauthIssuer:
		m.ResetOauthIssuer()
		return nil
	case appconfig.FieldOauthAudience:
		m.ResetOauthAudience()
		return nil
	case appconfig.FieldVlanScope:
		m.ResetVlanScope()
		return nil
	case appconfig.FieldEnableAuthentication:
		m.ResetEnableAuthentication()
		return nil
	}
	return fmt.Errorf("unknown AppConfig field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *AppConfigMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *AppConfigMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *AppConfigMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *AppConfigMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *AppConfigMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *AppConfigMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *AppConfigMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown AppConfig unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *AppConfigMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown AppConfig edge %s", name)
}

// InterfaceVlanStateMutation represents an operation that mutates the InterfaceVlanState nodes in the graph.
type InterfaceVlanStateMutation struct {
	config
	op                 Op
	typ                string
	id                 *int
	_interface         *string
	current_list       *string
	current_vlan_id    *int
	addcurrent_vlan_id *int
	last_synced_at     *time.Time
	clearedFields      map[string]struct{}
	done               bool
	oldValue           func(context.Context) (*InterfaceVlanState, error)
	predicates         []predicate.InterfaceVlanState
}

var _ ent.Mutation = (*InterfaceVlanStateMutation)(nil)

// interfacevlanstateOption allows management of the mutation configuration using functional options.
type interfacevlanstateOption func(*InterfaceVlanStateMutation)

// newInterfaceVlanStateMutation creates new mutation for the InterfaceVlanState entity.
func newInterfaceVlanStateMutation(c config, op Op, opts ...interfacevlanstateOption) *InterfaceVlanStateMutation {
	m := &InterfaceVlanStateMutation{
		config:        c,
		op:            op,
		typ:           TypeInterfaceVlanState,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withInterfaceVlanStateID sets the ID field of the mutation.
func withInterfaceVlanStateID(id int) interfacevlanstateOption {
	return func(m *InterfaceVlanStateMutation) {
		var (
			err   error
			once  sync.Once
			value *InterfaceVlanState
		)
		m.oldValue = func(ctx context.Context) (*InterfaceVlanState, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().InterfaceVlanState.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withInterfaceVlanState sets the old InterfaceVlanState of the mutation.
func withInterfaceVlanState(node *InterfaceVlanState) interfacevlanstateOption {
	return func(m *InterfaceVlanStateMutation) {
		m.oldValue = func(context.Context) (*InterfaceVlanState, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m InterfaceVlanStateMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m InterfaceVlanStateMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *InterfaceVlanStateMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *InterfaceVlanStateMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().InterfaceVlanState.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetInterface sets the "interface" field.
func (m *InterfaceVlanStateMutation) SetInterface(s string) {
	m._interface = &s
}

// Interface returns the value of the "interface" field in the mutation.
func (m *InterfaceVlanStateMutation) Interface() (r string, exists bool) {
	v := m._interface
	if v == nil {
		return
	}
	return *v, true
}

// OldInterface returns the old "interface" field's value of the InterfaceVlanState entity.
// If the InterfaceVlanState object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *InterfaceVlanStateMutation) OldInterface(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldInterface is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldInterface requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldInterface: %w", err)
	}
	return oldValue.Interface, nil
}

// ResetInterface resets all changes to the "interface" field.
func (m *InterfaceVlanStateMutation) ResetInterface() {
	m._interface = nil
}

// SetCurrentList sets the "current_list" field.
func (m *InterfaceVlanStateMutation) SetCurrentList(s string) {
	m.current_list = &s
}

// CurrentList returns the value of the "current_list" field in the mutation.
func (m *InterfaceVlanStateMutation) CurrentList() (r string, exists bool) {
	v := m.current_list
	if v == nil {
		return
	}
	return *v, true
}

// OldCurrentList returns the old "current_list" field's value of the InterfaceVlanState entity.
// If the InterfaceVlanState object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *InterfaceVlanStateMutation) OldCurrentList(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCurrentList is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCurrentList requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCurrentList: %w", err)
	}
	return oldValue.CurrentList, nil
}

// ResetCurrentList resets all changes to the "current_list" field.
func (m *InterfaceVlanStateMutation) ResetCurrentList() {
	m.current_list = nil
}

// SetCurrentVlanID sets the "current_vlan_id" field.
func (m *InterfaceVlanStateMutation) SetCurrentVlanID(i int) {
	m.current_vlan_id = &i
	m.addcurrent_vlan_id = nil
}

// CurrentVlanID returns the value of the "current_vlan_id" field in the mutation.
func (m *InterfaceVlanStateMutation) CurrentVlanID() (r int, exists bool) {
	v := m.current_vlan_id
	if v == nil {
		return
	}
	return *v, true
}

// OldCurrentVlanID returns the old "current_vlan_id" field's value of the InterfaceVlanState entity.
// If the InterfaceVlanState object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *InterfaceVlanStateMutation) OldCurrentVlanID(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCurrentVlanID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCurrentVlanID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCurrentVlanID: %w", err)
	}
	return oldValue.CurrentVlanID, nil
}

// AddCurrentVlanID adds i to the "current_vlan_id" field.
func (m *InterfaceVlanStateMutation) AddCurrentVlanID(i int) {
	if m.addcurrent_vlan_id != nil {
		*m.addcurrent_vlan_id += i
	} else {
		m.addcurrent_vlan_id = &i
	}
}

// AddedCurrentVlanID returns the value that was added to the "current_vlan_id" field in this mutation.
func (m *InterfaceVlanStateMutation) AddedCurrentVlanID() (r int, exists bool) {
	v := m.addcurrent_vlan_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetCurrentVlanID resets all changes to the "current_vlan_id" field.
func (m *InterfaceVlanStateMutation) ResetCurrentVlanID() {
	m.current_vlan_id = nil
	m.addcurrent_vlan_id = nil
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (m *InterfaceVlanStateMutation) SetLastSyncedAt(t time.Time) {
	m.last_synced_at = &t
}

// LastSyncedAt returns the value of the "last_synced_at" field in the mutation.
func (m *InterfaceVlanStateMutation) LastSyncedAt() (r time.Time, exists bool) {
	v := m.last_synced_at
	if v == nil {
		return
	}
	return *v, true
}

// OldLastSyncedAt returns the old "last_synced_at" field's value of the InterfaceVlanState entity.
// If the InterfaceVlanState object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *InterfaceVlanStateMutation) OldLastSyncedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLastSyncedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLastSyncedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLastSyncedAt: %w", err)
	}
	return oldValue.LastSyncedAt, nil
}

// ResetLastSyncedAt resets all changes to the "last_synced_at" field.
func (m *InterfaceVlanStateMutation) ResetLastSyncedAt() {
	m.last_synced_at = nil
}

// Where appends a list predicates to the InterfaceVlanStateMutation builder.
func (m *InterfaceVlanStateMutation) Where(ps ...predicate.InterfaceVlanState) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the InterfaceVlanStateMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *InterfaceVlanStateMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.InterfaceVlanState, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *InterfaceVlanStateMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *InterfaceVlanStateMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (InterfaceVlanState).
func (m *InterfaceVlanStateMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *InterfaceVlanStateMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m._interface != nil {
		fields = append(fields, interfacevlanstate.FieldInterface)
	}
	if m.current_list != nil {
		fields = append(fields, interfacevlanstate.FieldCurrentList)
	}
	if m.current_vlan_id != nil {
		fields = append(fields, interfacevlanstate.FieldCurrentVlanID)
	}
	if m.last_synced_at != nil {
		fields = append(fields, interfacevlanstate.FieldLastSyncedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *InterfaceVlanStateMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case interfacevlanstate.FieldInterface:
		return m.Interface()
	case interfacevlanstate.FieldCurrentList:
		return m.CurrentList()
	case interfacevlanstate.FieldCurrentVlanID:
		return m.CurrentVlanID()
	case interfacevlanstate.FieldLastSyncedAt:
		return m.LastSyncedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *InterfaceVlanStateMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case interfacevlanstate.FieldInterface:
		return m.OldInterface(ctx)
	case interfacevlanstate.FieldCurrentList:
		return m.OldCurrentList(ctx)
	case interfacevlanstate.FieldCurrentVlanID:
		return m.OldCurrentVlanID(ctx)
	case interfacevlanstate.FieldLastSyncedAt:
		return m.OldLastSyncedAt(ctx)
	}
	return nil, fmt.Errorf("unknown InterfaceVlanState field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *InterfaceVlanStateMutation) SetField(name string, value ent.Value) error {
	switch name {
	case interfacevlanstate.FieldInterface:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetInterface(v)
		return nil
	case interfacevlanstate.FieldCurrentList:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCurrentList(v)
		return nil
	case interfacevlanstate.FieldCurrentVlanID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCurrentVlanID(v)
		return nil
	case interfacevlanstate.FieldLastSyncedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLastSyncedAt(v)
		return nil
	}
	return fmt.Errorf("unknown InterfaceVlanState field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *InterfaceVlanStateMutation) AddedFields() []string {
	var fields []string
	if m.addcurrent_vlan_id != nil {
		fields = append(fields, interfacevlanstate.FieldCurrentVlanID)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *InterfaceVlanStateMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case interfacevlanstate.FieldCurrentVlanID:
		return m.AddedCurrentVlanID()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *InterfaceVlanStateMutation) AddField(name string, value ent.Value) error {
	switch name {
	case interfacevlanstate.FieldCurrentVlanID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddCurrentVlanID(v)
		return nil
	}
	return fmt.Errorf("unknown InterfaceVlanState numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *InterfaceVlanStateMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *InterfaceVlanStateMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *InterfaceVlanStateMutation) ClearField(name string) error {
	return fmt.Errorf("unknown InterfaceVlanState nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *InterfaceVlanStateMutation) ResetField(name string) error {
	switch name {
	case interfacevlanstate.FieldInterface:
		m.ResetInterface()
		return nil
	case interfacevlanstate.FieldCurrentList:
		m.ResetCurrentList()
		return nil
	case interfacevlanstate.FieldCurrentVlanID:
		m.ResetCurrentVlanID()
		return nil
	case interfacevlanstate.FieldLastSyncedAt:
		m.ResetLastSyncedAt()
		return nil
	}
	return fmt.Errorf("unknown InterfaceVlanState field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *InterfaceVlanStateMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *InterfaceVlanStateMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *InterfaceVlanStateMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *InterfaceVlanStateMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *InterfaceVlanStateMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *InterfaceVlanStateMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *InterfaceVlanStateMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown InterfaceVlanState unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *InterfaceVlanStateMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown InterfaceVlanState edge %s", name)
}

// RequestCmdMutation represents an operation that mutates the RequestCmd nodes in the graph.
type RequestCmdMutation struct {
	config
	op             Op
	typ            string
	id             *int
	timestamp      *time.Time
	command        *string
	args           *string
	_interface     *string
	success        *bool
	error          *string
	duration_ms    *int64
	addduration_ms *int64
	clearedFields  map[string]struct{}
	done           bool
	oldValue       func(context.Context) (*RequestCmd, error)
	predicates     []predicate.RequestCmd
}

var _ ent.Mutation = (*RequestCmdMutation)(nil)

// requestcmdOption allows management of the mutation configuration using functional options.
type requestcmdOption func(*RequestCmdMutation)

// newRequestCmdMutation creates new mutation for the RequestCmd entity.
func newRequestCmdMutation(c config, op Op, opts ...requestcmdOption) *RequestCmdMutation {
	m := &RequestCmdMutation{
		config:        c,
		op:            op,
		typ:           TypeRequestCmd,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withRequestCmdID sets the ID field of the mutation.
func withRequestCmdID(id int) requestcmdOption {
	return func(m *RequestCmdMutation) {
		var (
			err   error
			once  sync.Once
			value *RequestCmd
		)
		m.oldValue = func(ctx context.Context) (*RequestCmd, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().RequestCmd.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withRequestCmd sets the old RequestCmd of the mutation.
func withRequestCmd(node *RequestCmd) requestcmdOption {
	return func(m *RequestCmdMutation) {
		m.oldValue = func(context.Context) (*RequestCmd, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m RequestCmdMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m RequestCmdMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *RequestCmdMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *RequestCmdMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().RequestCmd.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetTimestamp sets the "timestamp" field.
func (m *RequestCmdMutation) SetTimestamp(t time.Time) {
	m.timestamp = &t
}

// Timestamp returns the value of the "timestamp" field in the mutation.
func (m *RequestCmdMutation) Timestamp() (r time.Time, exists bool) {
	v := m.timestamp
	if v == nil {
		return
	}
	return *v, true
}

// OldTimestamp returns the old "timestamp" field's value of the RequestCmd entity.
// If the RequestCmd object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RequestCmdMutation) OldTimestamp(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTimestamp is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTimestamp requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTimestamp: %w", err)
	}
	return oldValue.Timestamp, nil
}

// ResetTimestamp resets all changes to the "timestamp" field.
func (m *RequestCmdMutation) ResetTimestamp() {
	m.timestamp = nil
}

// SetCommand sets the "command" field.
func (m *RequestCmdMutation) SetCommand(s string) {
	m.command = &s
}

// Command returns the value of the "command" field in the mutation.
func (m *RequestCmdMutation) Command() (r string, exists bool) {
	v := m.command
	if v == nil {
		return
	}
	return *v, true
}

// OldCommand returns the old "command" field's value of the RequestCmd entity.
// If the RequestCmd object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RequestCmdMutation) OldCommand(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCommand is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCommand requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCommand: %w", err)
	}
	return oldValue.Command, nil
}

// ResetCommand resets all changes to the "command" field.
func (m *RequestCmdMutation) ResetCommand() {
	m.command = nil
}

// SetArgs sets the "args" field.
func (m *RequestCmdMutation) SetArgs(s string) {
	m.args = &s
}

// Args returns the value of the "args" field in the mutation.
func (m *RequestCmdMutation) Args() (r string, exists bool) {
	v := m.args
	if v == nil {
		return
	}
	return *v, true
}

// OldArgs returns the old "args" field's value of the RequestCmd entity.
// If the RequestCmd object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RequestCmdMutation) OldArgs(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldArgs is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldArgs requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldArgs: %w", err)
	}
	return oldValue.Args, nil
}

// ClearArgs clears the value of the "args" field.
func (m *RequestCmdMutation) ClearArgs() {
	m.args = nil
	m.clearedFields[requestcmd.FieldArgs] = struct{}{}
}

// ArgsCleared returns if the "args" field was cleared in this mutation.
func (m *RequestCmdMutation) ArgsCleared() bool {
	_, ok := m.clearedFields[requestcmd.FieldArgs]
	return ok
}

// ResetArgs resets all changes to the "args" field.
func (m *RequestCmdMutation) ResetArgs() {
	m.args = nil
	delete(m.clearedFields, requestcmd.FieldArgs)
}

// SetInterface sets the "interface" field.
func (m *RequestCmdMutation) SetInterface(s string) {
	m._interface = &s
}

// Interface returns the value of the "interface" field in the mutation.
func (m *RequestCmdMutation) Interface() (r string, exists bool) {
	v := m._interface
	if v == nil {
		return
	}
	return *v, true
}

// OldInterface returns the old "interface" field's value of the RequestCmd entity.
// If the RequestCmd object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RequestCmdMutation) OldInterface(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldInterface is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldInterface requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldInterface: %w", err)
	}
	return oldValue.Interface, nil
}

// ClearInterface clears the value of the "interface" field.
func (m *RequestCmdMutation) ClearInterface() {
	m._interface = nil
	m.clearedFields[requestcmd.FieldInterface] = struct{}{}
}

// InterfaceCleared returns if the "interface" field was cleared in this mutation.
func (m *RequestCmdMutation) InterfaceCleared() bool {
	_, ok := m.clearedFields[requestcmd.FieldInterface]
	return ok
}

// ResetInterface resets all changes to the "interface" field.
func (m *RequestCmdMutation) ResetInterface() {
	m._interface = nil
	delete(m.clearedFields, requestcmd.FieldInterface)
}

// SetSuccess sets the "success" field.
func (m *RequestCmdMutation) SetSuccess(b bool) {
	m.success = &b
}

// Success returns the value of the "success" field in the mutation.
func (m *RequestCmdMutation) Success() (r bool, exists bool) {
	v := m.success
	if v == nil {
		return
	}
	return *v, true
}

// OldSuccess returns the old "success" field's value of the RequestCmd entity.
// If the RequestCmd object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RequestCmdMutation) OldSuccess(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSuccess is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSuccess requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSuccess: %w", err)
	}
	return oldValue.Success, nil
}

// ResetSuccess resets all changes to the "success" field.
func (m *RequestCmdMutation) ResetSuccess() {
	m.success = nil
}

// SetError sets the "error" field.
func (m *RequestCmdMutation) SetError(s string) {
	m.error = &s
}

// Error returns the value of the "error" field in the mutation.
func (m *RequestCmdMutation) Error() (r string, exists bool) {
	v := m.error
	if v == nil {
		return
	}
	return *v, true
}

// OldError returns the old "error" field's value of the RequestCmd entity.
// If the RequestCmd object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RequestCmdMutation) OldError(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldError is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldError requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldError: %w", err)
	}
	return oldValue.Error, nil
}

// ClearError clears the value of the "error" field.
func (m *RequestCmdMutation) ClearError() {
	m.error = nil
	m.clearedFields[requestcmd.FieldError] = struct{}{}
}

// ErrorCleared returns if the "error" field was cleared in this mutation.
func (m *RequestCmdMutation) ErrorCleared() bool {
	_, ok := m.clearedFields[requestcmd.FieldError]
	return ok
}

// ResetError resets all changes to the "error" field.
func (m *RequestCmdMutation) ResetError() {
	m.error = nil
	delete(m.clearedFields, requestcmd.FieldError)
}

// SetDurationMs sets the "duration_ms" field.
func (m *RequestCmdMutation) SetDurationMs(i int64) {
	m.duration_ms = &i
	m.addduration_ms = nil
}

// DurationMs returns the value of the "duration_ms" field in the mutation.
func (m *RequestCmdMutation) DurationMs() (r int64, exists bool) {
	v := m.duration_ms
	if v == nil {
		return
	}
	return *v, true
}

// OldDurationMs returns the old "duration_ms" field's value of the RequestCmd entity.
// If the RequestCmd object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RequestCmdMutation) OldDurationMs(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDurationMs is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDurationMs requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDurationMs: %w", err)
	}
	return oldValue.DurationMs, nil
}

// AddDurationMs adds i to the "duration_ms" field.
func (m *RequestCmdMutation) AddDurationMs(i int64) {
	if m.addduration_ms != nil {
		*m.addduration_ms += i
	} else {
		m.addduration_ms = &i
	}
}

// AddedDurationMs returns the value that was added to the "duration_ms" field in this mutation.
func (m *RequestCmdMutation) AddedDurationMs() (r int64, exists bool) {
	v := m.addduration_ms
	if v == nil {
		return
	}
	return *v, true
}

// ResetDurationMs resets all changes to the "duration_ms" field.
func (m *RequestCmdMutation) ResetDurationMs() {
	m.duration_ms = nil
	m.addduration_ms = nil
}

// Where appends a list predicates to the RequestCmdMutation builder.
func (m *RequestCmdMutation) Where(ps ...predicate.RequestCmd) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the RequestCmdMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *RequestCmdMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.RequestCmd, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *RequestCmdMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *RequestCmdMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (RequestCmd).
func (m *RequestCmdMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *RequestCmdMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.timestamp != nil {
		fields = append(fields, requestcmd.FieldTimestamp)
	}
	if m.command != nil {
		fields = append(fields, requestcmd.FieldCommand)
	}
	if m.args != nil {
		fields = append(fields, requestcmd.FieldArgs)
	}
	if m._interface != nil {
		fields = append(fields, requestcmd.FieldInterface)
	}
	if m.success != nil {
		fields = append(fields, requestcmd.FieldSuccess)
	}
	if m.error != nil {
		fields = append(fields, requestcmd.FieldError)
	}
	if m.duration_ms != nil {
		fields = append(fields, requestcmd.FieldDurationMs)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *RequestCmdMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case requestcmd.FieldTimestamp:
		return m.Timestamp()
	case requestcmd.FieldCommand:
		return m.Command()
	case requestcmd.FieldArgs:
		return m.Args()
	case requestcmd.FieldInterface:
		return m.Interface()
	case requestcmd.FieldSuccess:
		return m.Success()
	case requestcmd.FieldError:
		return m.Error()
	case requestcmd.FieldDurationMs:
		return m.DurationMs()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *RequestCmdMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case requestcmd.FieldTimestamp:
		return m.OldTimestamp(ctx)
	case requestcmd.FieldCommand:
		return m.OldCommand(ctx)
	case requestcmd.FieldArgs:
		return m.OldArgs(ctx)
	case requestcmd.FieldInterface:
		return m.OldInterface(ctx)
	case requestcmd.FieldSuccess:
		return m.OldSuccess(ctx)
	case requestcmd.FieldError:
		return m.OldError(ctx)
	case requestcmd.FieldDurationMs:
		return m.OldDurationMs(ctx)
	}
	return nil, fmt.Errorf("unknown RequestCmd field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RequestCmdMutation) SetField(name string, value ent.Value) error {
	switch name {
	case requestcmd.FieldTimestamp:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTimestamp(v)
		return nil
	case requestcmd.FieldCommand:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCommand(v)
		return nil
	case requestcmd.FieldArgs:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetArgs(v)
		return nil
	case requestcmd.FieldInterface:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetInterface(v)
		return nil
	case requestcmd.FieldSuccess:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSuccess(v)
		return nil
	case requestcmd.FieldError:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetError(v)
		return nil
	case requestcmd.FieldDurationMs:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDurationMs(v)
		return nil
	}
	return fmt.Errorf("unknown RequestCmd field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *RequestCmdMutation) AddedFields() []string {
	var fields []string
	if m.addduration_ms != nil {
		fields = append(fields, requestcmd.FieldDurationMs)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *RequestCmdMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case requestcmd.FieldDurationMs:
		return m.AddedDurationMs()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RequestCmdMutation) AddField(name string, value ent.Value) error {
	switch name {
	case requestcmd.FieldDurationMs:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddDurationMs(v)
		return nil
	}
	return fmt.Errorf("unknown RequestCmd numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *RequestCmdMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(requestcmd.FieldArgs) {
		fields = append(fields, requestcmd.FieldArgs)
	}
	if m.FieldCleared(requestcmd.FieldInterface) {
		fields = append(fields, requestcmd.FieldInterface)
	}
	if m.FieldCleared(requestcmd.FieldError) {
		fields = append(fields, requestcmd.FieldError)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *RequestCmdMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *RequestCmdMutation) ClearField(name string) error {
	switch name {
	case requestcmd.FieldArgs:
		m.ClearArgs()
		return nil
	case requestcmd.FieldInterface:
		m.ClearInterface()
		return nil
	case requestcmd.FieldError:
		m.ClearError()
		return nil
	}
	return fmt.Errorf("unknown RequestCmd nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *RequestCmdMutation) ResetField(name string) error {
	switch name {
	case requestcmd.FieldTimestamp:
		m.ResetTimestamp()
		return nil
	case requestcmd.FieldCommand:
		m.ResetCommand()
		return nil
	case requestcmd.FieldArgs:
		m.ResetArgs()
		return nil
	case requestcmd.FieldInterface:
		m.ResetInterface()
		return nil
	case requestcmd.FieldSuccess:
		m.ResetSuccess()
		return nil
	case requestcmd.FieldError:
		m.ResetError()
		return nil
	case requestcmd.FieldDurationMs:
		m.ResetDurationMs()
		return nil
	}
	return fmt.Errorf("unknown RequestCmd field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *RequestCmdMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *RequestCmdMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *RequestCmdMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *RequestCmdMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *RequestCmdMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *RequestCmdMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *RequestCmdMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown RequestCmd unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *RequestCmdMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown RequestCmd edge %s", name)
}

// RequestLogMutation represents an operation that mutates the RequestLog nodes in the graph.
type RequestLogMutation struct {
	config
	op             Op
	typ            string
	id             *int
	timestamp      *time.Time
	method         *string
	_path          *string
	remote_addr    *string
	subject        *string
	_interface     *string
	vlan_id        *int
	addvlan_id     *int
	status_code    *int
	addstatus_code *int
	duration_ms    *int64
	addduration_ms *int64
	error          *string
	clearedFields  map[string]struct{}
	done           bool
	oldValue       func(context.Context) (*RequestLog, error)
	predicates     []predicate.RequestLog
}

var _ ent.Mutation = (*RequestLogMutation)(nil)

// requestlogOption allows management of the mutation configuration using functional options.
type requestlogOption func(*RequestLogMutation)

// newRequestLogMutation creates new mutation for the RequestLog entity.
func newRequestLogMutation(c config, op Op, opts ...requestlogOption) *RequestLogMutation {
	m := &RequestLogMutation{
		config:        c,
		op:            op,
		typ:           TypeRequestLog,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withRequestLogID sets the ID field of the mutation.
func withRequestLogID(id int) requestlogOption {
	return func(m *RequestLogMutation) {
		var (
			err   error
			once  sync.Once
			value *RequestLog
		)
		m.oldValue = func(ctx context.Context) (*RequestLog, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().RequestLog.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withRequestLog sets the old RequestLog of the mutation.
func withRequestLog(node *RequestLog) requestlogOption {
	return func(m *RequestLogMutation) {
		m.oldValue = func(context.Context) (*RequestLog, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m RequestLogMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m RequestLogMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *RequestLogMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *RequestLogMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().RequestLog.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetTimestamp sets the "timestamp" field.
func (m *RequestLogMutation) SetTimestamp(t time.Time) {
	m.timestamp = &t
}

// Timestamp returns the value of the "timestamp" field in the mutation.
func (m *RequestLogMutation) Timestamp() (r time.Time, exists bool) {
	v := m.timestamp
	if v == nil {
		return
	}
	return *v, true
}

// OldTimestamp returns the old "timestamp" field's value of the RequestLog entity.
// If the RequestLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RequestLogMutation) OldTimestamp(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTimestamp is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTimestamp requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTimestamp: %w", err)
	}
	return oldValue.Timestamp, nil
}

// ResetTimestamp resets all changes to the "timestamp" field.
func (m *RequestLogMutation) ResetTimestamp() {
	m.timestamp = nil
}

// SetMethod sets the "method" field.
func (m *RequestLogMutation) SetMethod(s string) {
	m.method = &s
}

// Method returns the value of the "method" field in the mutation.
func (m *RequestLogMutation) Method() (r string, exists bool) {
	v := m.method
	if v == nil {
		return
	}
	return *v, true
}

// OldMethod returns the old "method" field's value of the RequestLog entity.
// If the RequestLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RequestLogMutation) OldMethod(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMethod is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMethod requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMethod: %w", err)
	}
	return oldValue.Method, nil
}

// ResetMethod resets all changes to the "method" field.
func (m *RequestLogMutation) ResetMethod() {
	m.method = nil
}

// SetPath sets the "path" field.
func (m *RequestLogMutation) SetPath(s string) {
	m._path = &s
}

// Path returns the value of the "path" field in the mutation.
func (m *RequestLogMutation) Path() (r string, exists bool) {
	v := m._path
	if v == nil {
		return
	}
	return *v, true
}

// OldPath returns the old "path" field's value of the RequestLog entity.
// If the RequestLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RequestLogMutation) OldPath(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPath is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPath requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPath: %w", err)
	}
	return oldValue.Path, nil
}

// ResetPath resets all changes to the "path" field.
func (m *RequestLogMutation) ResetPath() {
	m._path = nil
}

// SetRemoteAddr sets the "remote_addr" field.
func (m *RequestLogMutation) SetRemoteAddr(s string) {
	m.remote_addr = &s
}

// RemoteAddr returns the value of the "remote_addr" field in the mutation.
func (m *RequestLogMutation) RemoteAddr() (r string, exists bool) {
	v := m.remote_addr
	if v == nil {
		return
	}
	return *v, true
}

// OldRemoteAddr returns the old "remote_addr" field's value of the RequestLog entity.
// If the RequestLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RequestLogMutation) OldRemoteAddr(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRemoteAddr is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRemoteAddr requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRemoteAddr: %w", err)
	}
	return oldValue.RemoteAddr, nil
}

// ResetRemoteAddr resets all changes to the "remote_addr" field.
func (m *RequestLogMutation) ResetRemoteAddr() {
	m.remote_addr = nil
}

// SetSubject sets the "subject" field.
func (m *RequestLogMutation) SetSubject(s string) {
	m.subject = &s
}

// Subject returns the value of the "subject" field in the mutation.
func (m *RequestLogMutation) Subject() (r string, exists bool) {
	v := m.subject
	if v == nil {
		return
	}
	return *v, true
}

// OldSubject returns the old "subject" field's value of the RequestLog entity.
// If the RequestLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RequestLogMutation) OldSubject(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSubject is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSubject requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSubject: %w", err)
	}
	return oldValue.Subject, nil
}

// ClearSubject clears the value of the "subject" field.
func (m *RequestLogMutation) ClearSubject() {
	m.subject = nil
	m.clearedFields[requestlog.FieldSubject] = struct{}{}
}

// SubjectCleared returns if the "subject" field was cleared in this mutation.
func (m *RequestLogMutation) SubjectCleared() bool {
	_, ok := m.clearedFields[requestlog.FieldSubject]
	return ok
}

// ResetSubject resets all changes to the "subject" field.
func (m *RequestLogMutation) ResetSubject() {
	m.subject = nil
	delete(m.clearedFields, requestlog.FieldSubject)
}

// SetInterface sets the "interface" field.
func (m *RequestLogMutation) SetInterface(s string) {
	m._interface = &s
}

// Interface returns the value of the "interface" field in the mutation.
func (m *RequestLogMutation) Interface() (r string, exists bool) {
	v := m._interface
	if v == nil {
		return
	}
	return *v, true
}

// OldInterface returns the old "interface" field's value of the RequestLog entity.
// If the RequestLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RequestLogMutation) OldInterface(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldInterface is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldInterface requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldInterface: %w", err)
	}
	return oldValue.Interface, nil
}

// ClearInterface clears the value of the "interface" field.
func (m *RequestLogMutation) ClearInterface() {
	m._interface = nil
	m.clearedFields[requestlog.FieldInterface] = struct{}{}
}

// InterfaceCleared returns if the "interface" field was cleared in this mutation.
func (m *RequestLogMutation) InterfaceCleared() bool {
	_, ok := m.clearedFields[requestlog.FieldInterface]
	return ok
}

// ResetInterface resets all changes to the "interface" field.
func (m *RequestLogMutation) ResetInterface() {
	m._interface = nil
	delete(m.clearedFields, requestlog.FieldInterface)
}

// SetVlanID sets the "vlan_id" field.
func (m *RequestLogMutation) SetVlanID(i int) {
	m.vlan_id = &i
	m.addvlan_id = nil
}

// VlanID returns the value of the "vlan_id" field in the mutation.
func (m *RequestLogMutation) VlanID() (r int, exists bool) {
	v := m.vlan_id
	if v == nil {
		return
	}
	return *v, true
}

// OldVlanID returns the old "vlan_id" field's value of the RequestLog entity.
// If the RequestLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RequestLogMutation) OldVlanID(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldVlanID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldVlanID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldVlanID: %w", err)
	}
	return oldValue.VlanID, nil
}

// AddVlanID adds i to the "vlan_id" field.
func (m *RequestLogMutation) AddVlanID(i int) {
	if m.addvlan_id != nil {
		*m.addvlan_id += i
	} else {
		m.addvlan_id = &i
	}
}

// AddedVlanID returns the value that was added to the "vlan_id" field in this mutation.
func (m *RequestLogMutation) AddedVlanID() (r int, exists bool) {
	v := m.addvlan_id
	if v == nil {
		return
	}
	return *v, true
}

// ClearVlanID clears the value of the "vlan_id" field.
func (m *RequestLogMutation) ClearVlanID() {
	m.vlan_id = nil
	m.addvlan_id = nil
	m.clearedFields[requestlog.FieldVlanID] = struct{}{}
}

// VlanIDCleared returns if the "vlan_id" field was cleared in this mutation.
func (m *RequestLogMutation) VlanIDCleared() bool {
	_, ok := m.clearedFields[requestlog.FieldVlanID]
	return ok
}

// ResetVlanID resets all changes to the "vlan_id" field.
func (m *RequestLogMutation) ResetVlanID() {
	m.vlan_id = nil
	m.addvlan_id = nil
	delete(m.clearedFields, requestlog.FieldVlanID)
}

// SetStatusCode sets the "status_code" field.
func (m *RequestLogMutation) SetStatusCode(i int) {
	m.status_code = &i
	m.addstatus_code = nil
}

// StatusCode returns the value of the "status_code" field in the mutation.
func (m *RequestLogMutation) StatusCode() (r int, exists bool) {
	v := m.status_code
	if v == nil {
		return
	}
	return *v, true
}

// OldStatusCode returns the old "status_code" field's value of the RequestLog entity.
// If the RequestLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RequestLogMutation) OldStatusCode(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatusCode is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatusCode requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatusCode: %w", err)
	}
	return oldValue.StatusCode, nil
}

// AddStatusCode adds i to the "status_code" field.
func (m *RequestLogMutation) AddStatusCode(i int) {
	if m.addstatus_code != nil {
		*m.addstatus_code += i
	} else {
		m.addstatus_code = &i
	}
}

// AddedStatusCode returns the value that was added to the "status_code" field in this mutation.
func (m *RequestLogMutation) AddedStatusCode() (r int, exists bool) {
	v := m.addstatus_code
	if v == nil {
		return
	}
	return *v, true
}

// ResetStatusCode resets all changes to the "status_code" field.
func (m *RequestLogMutation) ResetStatusCode() {
	m.status_code = nil
	m.addstatus_code = nil
}

// SetDurationMs sets the "duration_ms" field.
func (m *RequestLogMutation) SetDurationMs(i int64) {
	m.duration_ms = &i
	m.addduration_ms = nil
}

// DurationMs returns the value of the "duration_ms" field in the mutation.
func (m *RequestLogMutation) DurationMs() (r int64, exists bool) {
	v := m.duration_ms
	if v == nil {
		return
	}
	return *v, true
}

// OldDurationMs returns the old "duration_ms" field's value of the RequestLog entity.
// If the RequestLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RequestLogMutation) OldDurationMs(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDurationMs is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDurationMs requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDurationMs: %w", err)
	}
	return oldValue.DurationMs, nil
}

// AddDurationMs adds i to the "duration_ms" field.
func (m *RequestLogMutation) AddDurationMs(i int64) {
	if m.addduration_ms != nil {
		*m.addduration_ms += i
	} else {
		m.addduration_ms = &i
	}
}

// AddedDurationMs returns the value that was added to the "duration_ms" field in this mutation.
func (m *RequestLogMutation) AddedDurationMs() (r int64, exists bool) {
	v := m.addduration_ms
	if v == nil {
		return
	}
	return *v, true
}

// ResetDurationMs resets all changes to the "duration_ms" field.
func (m *RequestLogMutation) ResetDurationMs() {
	m.duration_ms = nil
	m.addduration_ms = nil
}

// SetError sets the "error" field.
func (m *RequestLogMutation) SetError(s string) {
	m.error = &s
}

// Error returns the value of the "error" field in the mutation.
func (m *RequestLogMutation) Error() (r string, exists bool) {
	v := m.error
	if v == nil {
		return
	}
	return *v, true
}

// OldError returns the old "error" field's value of the RequestLog entity.
// If the RequestLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RequestLogMutation) OldError(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldError is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldError requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldError: %w", err)
	}
	return oldValue.Error, nil
}

// ClearError clears the value of the "error" field.
func (m *RequestLogMutation) ClearError() {
	m.error = nil
	m.clearedFields[requestlog.FieldError] = struct{}{}
}

// ErrorCleared returns if the "error" field was cleared in this mutation.
func (m *RequestLogMutation) ErrorCleared() bool {
	_, ok := m.clearedFields[requestlog.FieldError]
	return ok
}

// ResetError resets all changes to the "error" field.
func (m *RequestLogMutation) ResetError() {
	m.error = nil
	delete(m.clearedFields, requestlog.FieldError)
}

// Where appends a list predicates to the RequestLogMutation builder.
func (m *RequestLogMutation) Where(ps ...predicate.RequestLog) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the RequestLogMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *RequestLogMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.RequestLog, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *RequestLogMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *RequestLogMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (RequestLog).
func (m *RequestLogMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *RequestLogMutation) Fields() []string {
	fields := make([]string, 0, 10)
	if m.timestamp != nil {
		fields = append(fields, requestlog.FieldTimestamp)
	}
	if m.method != nil {
		fields = append(fields, requestlog.FieldMethod)
	}
	if m._path != nil {
		fields = append(fields, requestlog.FieldPath)
	}
	if m.remote_addr != nil {
		fields = append(fields, requestlog.FieldRemoteAddr)
	}
	if m.subject != nil {
		fields = append(fields, requestlog.FieldSubject)
	}
	if m._interface != nil {
		fields = append(fields, requestlog.FieldInterface)
	}
	if m.vlan_id != nil {
		fields = append(fields, requestlog.FieldVlanID)
	}
	if m.status_code != nil {
		fields = append(fields, requestlog.FieldStatusCode)
	}
	if m.duration_ms != nil {
		fields = append(fields, requestlog.FieldDurationMs)
	}
	if m.error != nil {
		fields = append(fields, requestlog.FieldError)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *RequestLogMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case requestlog.FieldTimestamp:
		return m.Timestamp()
	case requestlog.FieldMethod:
		return m.Method()
	case requestlog.FieldPath:
		return m.Path()
	case requestlog.FieldRemoteAddr:
		return m.RemoteAddr()
	case requestlog.FieldSubject:
		return m.Subject()
	case requestlog.FieldInterface:
		return m.Interface()
	case requestlog.FieldVlanID:
		return m.VlanID()
	case requestlog.FieldStatusCode:
		return m.StatusCode()
	case requestlog.FieldDurationMs:
		return m.DurationMs()
	case requestlog.FieldError:
		return m.Error()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *RequestLogMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case requestlog.FieldTimestamp:
		return m.OldTimestamp(ctx)
	case requestlog.FieldMethod:
		return m.OldMethod(ctx)
	case requestlog.FieldPath:
		return m.OldPath(ctx)
	case requestlog.FieldRemoteAddr:
		return m.OldRemoteAddr(ctx)
	case requestlog.FieldSubject:
		return m.OldSubject(ctx)
	case requestlog.FieldInterface:
		return m.OldInterface(ctx)
	case requestlog.FieldVlanID:
		return m.OldVlanID(ctx)
	case requestlog.FieldStatusCode:
		return m.OldStatusCode(ctx)
	case requestlog.FieldDurationMs:
		return m.OldDurationMs(ctx)
	case requestlog.FieldError:
		return m.OldError(ctx)
	}
	return nil, fmt.Errorf("unknown RequestLog field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RequestLogMutation) SetField(name string, value ent.Value) error {
	switch name {
	case requestlog.FieldTimestamp:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTimestamp(v)
		return nil
	case requestlog.FieldMethod:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMethod(v)
		return nil
	case requestlog.FieldPath:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPath(v)
		return nil
	case requestlog.FieldRemoteAddr:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRemoteAddr(v)
		return nil
	case requestlog.FieldSubject:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSubject(v)
		return nil
	case requestlog.FieldInterface:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetInterface(v)
		return nil
	case requestlog.FieldVlanID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetVlanID(v)
		return nil
	case requestlog.FieldStatusCode:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatusCode(v)
		return nil
	case requestlog.FieldDurationMs:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDurationMs(v)
		return nil
	case requestlog.FieldError:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetError(v)
		return nil
	}
	return fmt.Errorf("unknown RequestLog field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *RequestLogMutation) AddedFields() []string {
	var fields []string
	if m.addvlan_id != nil {
		fields = append(fields, requestlog.FieldVlanID)
	}
	if m.addstatus_code != nil {
		fields = append(fields, requestlog.FieldStatusCode)
	}
	if m.addduration_ms != nil {
		fields = append(fields, requestlog.FieldDurationMs)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *RequestLogMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case requestlog.FieldVlanID:
		return m.AddedVlanID()
	case requestlog.FieldStatusCode:
		return m.AddedStatusCode()
	case requestlog.FieldDurationMs:
		return m.AddedDurationMs()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RequestLogMutation) AddField(name string, value ent.Value) error {
	switch name {
	case requestlog.FieldVlanID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddVlanID(v)
		return nil
	case requestlog.FieldStatusCode:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddStatusCode(v)
		return nil
	case requestlog.FieldDurationMs:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddDurationMs(v)
		return nil
	}
	return fmt.Errorf("unknown RequestLog numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *RequestLogMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(requestlog.FieldSubject) {
		fields = append(fields, requestlog.FieldSubject)
	}
	if m.FieldCleared(requestlog.FieldInterface) {
		fields = append(fields, requestlog.FieldInterface)
	}
	if m.FieldCleared(requestlog.FieldVlanID) {
		fields = append(fields, requestlog.FieldVlanID)
	}
	if m.FieldCleared(requestlog.FieldError) {
		fields = append(fields, requestlog.FieldError)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *RequestLogMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *RequestLogMutation) ClearField(name string) error {
	switch name {
	case requestlog.FieldSubject:
		m.ClearSubject()
		return nil
	case requestlog.FieldInterface:
		m.ClearInterface()
		return nil
	case requestlog.FieldVlanID:
		m.ClearVlanID()
		return nil
	case requestlog.FieldError:
		m.ClearError()
		return nil
	}
	return fmt.Errorf("unknown RequestLog nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *RequestLogMutation) ResetField(name string) error {
	switch name {
	case requestlog.FieldTimestamp:
		m.ResetTimestamp()
		return nil
	case requestlog.FieldMethod:
		m.ResetMethod()
		return nil
	case requestlog.FieldPath:
		m.ResetPath()
		return nil
	case requestlog.FieldRemoteAddr:
		m.ResetRemoteAddr()
		return nil
	case requestlog.FieldSubject:
		m.ResetSubject()
		return nil
	case requestlog.FieldInterface:
		m.ResetInterface()
		return nil
	case requestlog.FieldVlanID:
		m.ResetVlanID()
		return nil
	case requestlog.FieldStatusCode:
		m.ResetStatusCode()
		return nil
	case requestlog.FieldDurationMs:
		m.ResetDurationMs()
		return nil
	case requestlog.FieldError:
		m.ResetError()
		return nil
	}
	return fmt.Errorf("unknown RequestLog field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *RequestLogMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *RequestLogMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *RequestLogMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *RequestLogMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *RequestLogMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *RequestLogMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *RequestLogMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown RequestLog unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *RequestLogMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown RequestLog edge %s", name)
}
