// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"go-mikrotik-vlan-switcher/ent/predicate"
	"go-mikrotik-vlan-switcher/ent/requestcmd"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RequestCmdDelete is the builder for deleting a RequestCmd entity.
type RequestCmdDelete struct {
	config
	hooks    []Hook
	mutation *RequestCmdMutation
}

// Where appends a list predicates to the RequestCmdDelete builder.
func (_d *RequestCmdDelete) Where(ps ...predicate.RequestCmd) *RequestCmdDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RequestCmdDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RequestCmdDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RequestCmdDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(requestcmd.Table, sqlgraph.NewFieldSpec(requestcmd.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RequestCmdDeleteOne is the builder for deleting a single RequestCmd entity.
type RequestCmdDeleteOne struct {
	_d *RequestCmdDelete
}

// Where appends a list predicates to the RequestCmdDelete builder.
func (_d *RequestCmdDeleteOne) Where(ps ...predicate.RequestCmd) *RequestCmdDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RequestCmdDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{requestcmd.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RequestCmdDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
