// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-mikrotik-vlan-switcher/ent/requestlog"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RequestLogCreate is the builder for creating a RequestLog entity.
type RequestLogCreate struct {
	config
	mutation *RequestLogMutation
	hooks    []Hook
}

// SetTimestamp sets the "timestamp" field.
func (_c *RequestLogCreate) SetTimestamp(v time.Time) *RequestLogCreate {
	_c.mutation.SetTimestamp(v)
	return _c
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_c *RequestLogCreate) SetNillableTimestamp(v *time.Time) *RequestLogCreate {
	if v != nil {
		_c.SetTimestamp(*v)
	}
	return _c
}

// SetMethod sets the "method" field.
func (_c *RequestLogCreate) SetMethod(v string) *RequestLogCreate {
	_c.mutation.SetMethod(v)
	return _c
}

// SetPath sets the "path" field.
func (_c *RequestLogCreate) SetPath(v string) *RequestLogCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetRemoteAddr sets the "remote_addr" field.
func (_c *RequestLogCreate) SetRemoteAddr(v string) *RequestLogCreate {
	_c.mutation.SetRemoteAddr(v)
	return _c
}

// SetSubject sets the "subject" field.
func (_c *RequestLogCreate) SetSubject(v string) *RequestLogCreate {
	_c.mutation.SetSubject(v)
	return _c
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_c *RequestLogCreate) SetNillableSubject(v *string) *RequestLogCreate {
	if v != nil {
		_c.SetSubject(*v)
	}
	return _c
}

// SetInterface sets the "interface" field.
func (_c *RequestLogCreate) SetInterface(v string) *RequestLogCreate {
	_c.mutation.SetInterface(v)
	return _c
}

// SetNillableInterface sets the "interface" field if the given value is not nil.
func (_c *RequestLogCreate) SetNillableInterface(v *string) *RequestLogCreate {
	if v != nil {
		_c.SetInterface(*v)
	}
	return _c
}

// SetVlanID sets the "vlan_id" field.
func (_c *RequestLogCreate) SetVlanID(v int) *RequestLogCreate {
	_c.mutation.SetVlanID(v)
	return _c
}

// SetNillableVlanID sets the "vlan_id" field if the given value is not nil.
func (_c *RequestLogCreate) SetNillableVlanID(v *int) *RequestLogCreate {
	if v != nil {
		_c.SetVlanID(*v)
	}
	return _c
}

// SetStatusCode sets the "status_code" field.
func (_c *RequestLogCreate) SetStatusCode(v int) *RequestLogCreate {
	_c.mutation.SetStatusCode(v)
	return _c
}

// SetDurationMs sets the "duration_ms" field.
func (_c *RequestLogCreate) SetDurationMs(v int64) *RequestLogCreate {
	_c.mutation.SetDurationMs(v)
	return _c
}

// SetError sets the "error" field.
func (_c *RequestLogCreate) SetError(v string) *RequestLogCreate {
	_c.mutation.SetError(v)
	return _c
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_c *RequestLogCreate) SetNillableError(v *string) *RequestLogCreate {
	if v != nil {
		_c.SetError(*v)
	}
	return _c
}

// Mutation returns the RequestLogMutation object of the builder.
func (_c *RequestLogCreate) Mutation() *RequestLogMutation {
	return _c.mutation
}

// Save creates the RequestLog in the database.
func (_c *RequestLogCreate) Save(ctx context.Context) (*RequestLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RequestLogCreate) SaveX(ctx context.Context) *RequestLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequestLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequestLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RequestLogCreate) defaults() {
	if _, ok := _c.mutation.Timestamp(); !ok {
		v := requestlog.DefaultTimestamp()
		_c.mutation.SetTimestamp(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RequestLogCreate) check() error {
	if _, ok := _c.mutation.Timestamp(); !ok {
		return &ValidationError{Name: "timestamp", err: errors.New(`ent: missing required field "RequestLog.timestamp"`)}
	}
	if _, ok := _c.mutation.Method(); !ok {
		return &ValidationError{Name: "method", err: errors.New(`ent: missing required field "RequestLog.method"`)}
	}
	if _, ok := _c.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "RequestLog.path"`)}
	}
	if _, ok := _c.mutation.RemoteAddr(); !ok {
		return &ValidationError{Name: "remote_addr", err: errors.New(`ent: missing required field "RequestLog.remote_addr"`)}
	}
	if _, ok := _c.mutation.StatusCode(); !ok {
		return &ValidationError{Name: "status_code", err: errors.New(`ent: missing required field "RequestLog.status_code"`)}
	}
	if _, ok := _c.mutation.DurationMs(); !ok {
		return &ValidationError{Name: "duration_ms", err: errors.New(`ent: missing required field "RequestLog.duration_ms"`)}
	}
	return nil
}

func (_c *RequestLogCreate) sqlSave(ctx context.Context) (*RequestLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RequestLogCreate) createSpec() (*RequestLog, *sqlgraph.CreateSpec) {
	var (
		_node = &RequestLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(requestlog.Table, sqlgraph.NewFieldSpec(requestlog.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Timestamp(); ok {
		_spec.SetField(requestlog.FieldTimestamp, field.TypeTime, value)
		_node.Timestamp = value
	}
	if value, ok := _c.mutation.Method(); ok {
		_spec.SetField(requestlog.FieldMethod, field.TypeString, value)
		_node.Method = value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(requestlog.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := _c.mutation.RemoteAddr(); ok {
		_spec.SetField(requestlog.FieldRemoteAddr, field.TypeString, value)
		_node.RemoteAddr = value
	}
	if value, ok := _c.mutation.Subject(); ok {
		_spec.SetField(requestlog.FieldSubject, field.TypeString, value)
		_node.Subject = value
	}
	if value, ok := _c.mutation.Interface(); ok {
		_spec.SetField(requestlog.FieldInterface, field.TypeString, value)
		_node.Interface = value
	}
	if value, ok := _c.mutation.VlanID(); ok {
		_spec.SetField(requestlog.FieldVlanID, field.TypeInt, value)
		_node.VlanID = value
	}
	if value, ok := _c.mutation.StatusCode(); ok {
		_spec.SetField(requestlog.FieldStatusCode, field.TypeInt, value)
		_node.StatusCode = value
	}
	if value, ok := _c.mutation.DurationMs(); ok {
		_spec.SetField(requestlog.FieldDurationMs, field.TypeInt64, value)
		_node.DurationMs = value
	}
	if value, ok := _c.mutation.Error(); ok {
		_spec.SetField(requestlog.FieldError, field.TypeString, value)
		_node.Error = value
	}
	return _node, _spec
}

// RequestLogCreateBulk is the builder for creating many RequestLog entities in bulk.
type RequestLogCreateBulk struct {
	config
	err      error
	builders []*RequestLogCreate
}

// Save creates the RequestLog entities in the database.
func (_c *RequestLogCreateBulk) Save(ctx context.Context) ([]*RequestLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RequestLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RequestLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RequestLogCreateBulk) SaveX(ctx context.Context) []*RequestLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequestLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequestLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
