// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"go-mikrotik-vlan-switcher/ent/requestcmd"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// RequestCmd is the model entity for the RequestCmd schema.
type RequestCmd struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Timestamp holds the value of the "timestamp" field.
	Timestamp time.Time `json:"timestamp,omitempty"`
	// Command holds the value of the "command" field.
	Command string `json:"command,omitempty"`
	// Args holds the value of the "args" field.
	Args string `json:"args,omitempty"`
	// Interface holds the value of the "interface" field.
	Interface string `json:"interface,omitempty"`
	// Success holds the value of the "success" field.
	Success bool `json:"success,omitempty"`
	// Error holds the value of the "error" field.
	Error string `json:"error,omitempty"`
	// DurationMs holds the value of the "duration_ms" field.
	DurationMs   int64 `json:"duration_ms,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RequestCmd) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case requestcmd.FieldSuccess:
			values[i] = new(sql.NullBool)
		case requestcmd.FieldID, requestcmd.FieldDurationMs:
			values[i] = new(sql.NullInt64)
		case requestcmd.FieldCommand, requestcmd.FieldArgs, requestcmd.FieldInterface, requestcmd.FieldError:
			values[i] = new(sql.NullString)
		case requestcmd.FieldTimestamp:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RequestCmd fields.
func (_m *RequestCmd) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case requestcmd.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case requestcmd.FieldTimestamp:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field timestamp", values[i])
			} else if value.Valid {
				_m.Timestamp = value.Time
			}
		case requestcmd.FieldCommand:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field command", values[i])
			} else if value.Valid {
				_m.Command = value.String
			}
		case requestcmd.FieldArgs:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field args", values[i])
			} else if value.Valid {
				_m.Args = value.String
			}
		case requestcmd.FieldInterface:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field interface", values[i])
			} else if value.Valid {
				_m.Interface = value.String
			}
		case requestcmd.FieldSuccess:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field success", values[i])
			} else if value.Valid {
				_m.Success = value.Bool
			}
		case requestcmd.FieldError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error", values[i])
			} else if value.Valid {
				_m.Error = value.String
			}
		case requestcmd.FieldDurationMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_ms", values[i])
			} else if value.Valid {
				_m.DurationMs = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RequestCmd.
// This includes values selected through modifiers, order, etc.
func (_m *RequestCmd) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this RequestCmd.
// Note that you need to call RequestCmd.Unwrap() before calling this method if this RequestCmd
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RequestCmd) Update() *RequestCmdUpdateOne {
	return NewRequestCmdClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RequestCmd entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RequestCmd) Unwrap() *RequestCmd {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RequestCmd is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RequestCmd) String() string {
	var builder strings.Builder
	builder.WriteString("RequestCmd(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("timestamp=")
	builder.WriteString(_m.Timestamp.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("command=")
	builder.WriteString(_m.Command)
	builder.WriteString(", ")
	builder.WriteString("args=")
	builder.WriteString(_m.Args)
	builder.WriteString(", ")
	builder.WriteString("interface=")
	builder.WriteString(_m.Interface)
	builder.WriteString(", ")
	builder.WriteString("success=")
	builder.WriteString(fmt.Sprintf("%v", _m.Success))
	builder.WriteString(", ")
	builder.WriteString("error=")
	builder.WriteString(_m.Error)
	builder.WriteString(", ")
	builder.WriteString("duration_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.DurationMs))
	builder.WriteByte(')')
	return builder.String()
}

// RequestCmds is a parsable slice of RequestCmd.
type RequestCmds []*RequestCmd
