// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-mikrotik-vlan-switcher/ent/predicate"
	"go-mikrotik-vlan-switcher/ent/requestcmd"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RequestCmdUpdate is the builder for updating RequestCmd entities.
type RequestCmdUpdate struct {
	config
	hooks    []Hook
	mutation *RequestCmdMutation
}

// Where appends a list predicates to the RequestCmdUpdate builder.
func (_u *RequestCmdUpdate) Where(ps ...predicate.RequestCmd) *RequestCmdUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTimestamp sets the "timestamp" field.
func (_u *RequestCmdUpdate) SetTimestamp(v time.Time) *RequestCmdUpdate {
	_u.mutation.SetTimestamp(v)
	return _u
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_u *RequestCmdUpdate) SetNillableTimestamp(v *time.Time) *RequestCmdUpdate {
	if v != nil {
		_u.SetTimestamp(*v)
	}
	return _u
}

// SetCommand sets the "command" field.
func (_u *RequestCmdUpdate) SetCommand(v string) *RequestCmdUpdate {
	_u.mutation.SetCommand(v)
	return _u
}

// SetNillableCommand sets the "command" field if the given value is not nil.
func (_u *RequestCmdUpdate) SetNillableCommand(v *string) *RequestCmdUpdate {
	if v != nil {
		_u.SetCommand(*v)
	}
	return _u
}

// SetArgs sets the "args" field.
func (_u *RequestCmdUpdate) SetArgs(v string) *RequestCmdUpdate {
	_u.mutation.SetArgs(v)
	return _u
}

// SetNillableArgs sets the "args" field if the given value is not nil.
func (_u *RequestCmdUpdate) SetNillableArgs(v *string) *RequestCmdUpdate {
	if v != nil {
		_u.SetArgs(*v)
	}
	return _u
}

// ClearArgs clears the value of the "args" field.
func (_u *RequestCmdUpdate) ClearArgs() *RequestCmdUpdate {
	_u.mutation.ClearArgs()
	return _u
}

// SetInterface sets the "interface" field.
func (_u *RequestCmdUpdate) SetInterface(v string) *RequestCmdUpdate {
	_u.mutation.SetInterface(v)
	return _u
}

// SetNillableInterface sets the "interface" field if the given value is not nil.
func (_u *RequestCmdUpdate) SetNillableInterface(v *string) *RequestCmdUpdate {
	if v != nil {
		_u.SetInterface(*v)
	}
	return _u
}

// ClearInterface clears the value of the "interface" field.
func (_u *RequestCmdUpdate) ClearInterface() *RequestCmdUpdate {
	_u.mutation.ClearInterface()
	return _u
}

// SetSuccess sets the "success" field.
func (_u *RequestCmdUpdate) SetSuccess(v bool) *RequestCmdUpdate {
	_u.mutation.SetSuccess(v)
	return _u
}

// SetNillableSuccess sets the "success" field if the given value is not nil.
func (_u *RequestCmdUpdate) SetNillableSuccess(v *bool) *RequestCmdUpdate {
	if v != nil {
		_u.SetSuccess(*v)
	}
	return _u
}

// SetError sets the "error" field.
func (_u *RequestCmdUpdate) SetError(v string) *RequestCmdUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *RequestCmdUpdate) SetNillableError(v *string) *RequestCmdUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *RequestCmdUpdate) ClearError() *RequestCmdUpdate {
	_u.mutation.ClearError()
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *RequestCmdUpdate) SetDurationMs(v int64) *RequestCmdUpdate {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *RequestCmdUpdate) SetNillableDurationMs(v *int64) *RequestCmdUpdate {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *RequestCmdUpdate) AddDurationMs(v int64) *RequestCmdUpdate {
	_u.mutation.AddDurationMs(v)
	return _u
}

// Mutation returns the RequestCmdMutation object of the builder.
func (_u *RequestCmdUpdate) Mutation() *RequestCmdMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RequestCmdUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequestCmdUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RequestCmdUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequestCmdUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RequestCmdUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(requestcmd.Table, requestcmd.Columns, sqlgraph.NewFieldSpec(requestcmd.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Timestamp(); ok {
		_spec.SetField(requestcmd.FieldTimestamp, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Command(); ok {
		_spec.SetField(requestcmd.FieldCommand, field.TypeString, value)
	}
	if value, ok := _u.mutation.Args(); ok {
		_spec.SetField(requestcmd.FieldArgs, field.TypeString, value)
	}
	if _u.mutation.ArgsCleared() {
		_spec.ClearField(requestcmd.FieldArgs, field.TypeString)
	}
	if value, ok := _u.mutation.Interface(); ok {
		_spec.SetField(requestcmd.FieldInterface, field.TypeString, value)
	}
	if _u.mutation.InterfaceCleared() {
		_spec.ClearField(requestcmd.FieldInterface, field.TypeString)
	}
	if value, ok := _u.mutation.Success(); ok {
		_spec.SetField(requestcmd.FieldSuccess, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(requestcmd.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(requestcmd.FieldError, field.TypeString)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(requestcmd.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(requestcmd.FieldDurationMs, field.TypeInt64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{requestcmd.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RequestCmdUpdateOne is the builder for updating a single RequestCmd entity.
type RequestCmdUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RequestCmdMutation
}

// SetTimestamp sets the "timestamp" field.
func (_u *RequestCmdUpdateOne) SetTimestamp(v time.Time) *RequestCmdUpdateOne {
	_u.mutation.SetTimestamp(v)
	return _u
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_u *RequestCmdUpdateOne) SetNillableTimestamp(v *time.Time) *RequestCmdUpdateOne {
	if v != nil {
		_u.SetTimestamp(*v)
	}
	return _u
}

// SetCommand sets the "command" field.
func (_u *RequestCmdUpdateOne) SetCommand(v string) *RequestCmdUpdateOne {
	_u.mutation.SetCommand(v)
	return _u
}

// SetNillableCommand sets the "command" field if the given value is not nil.
func (_u *RequestCmdUpdateOne) SetNillableCommand(v *string) *RequestCmdUpdateOne {
	if v != nil {
		_u.SetCommand(*v)
	}
	return _u
}

// SetArgs sets the "args" field.
func (_u *RequestCmdUpdateOne) SetArgs(v string) *RequestCmdUpdateOne {
	_u.mutation.SetArgs(v)
	return _u
}

// SetNillableArgs sets the "args" field if the given value is not nil.
func (_u *RequestCmdUpdateOne) SetNillableArgs(v *string) *RequestCmdUpdateOne {
	if v != nil {
		_u.SetArgs(*v)
	}
	return _u
}

// ClearArgs clears the value of the "args" field.
func (_u *RequestCmdUpdateOne) ClearArgs() *RequestCmdUpdateOne {
	_u.mutation.ClearArgs()
	return _u
}

// SetInterface sets the "interface" field.
func (_u *RequestCmdUpdateOne) SetInterface(v string) *RequestCmdUpdateOne {
	_u.mutation.SetInterface(v)
	return _u
}

// SetNillableInterface sets the "interface" field if the given value is not nil.
func (_u *RequestCmdUpdateOne) SetNillableInterface(v *string) *RequestCmdUpdateOne {
	if v != nil {
		_u.SetInterface(*v)
	}
	return _u
}

// ClearInterface clears the value of the "interface" field.
func (_u *RequestCmdUpdateOne) ClearInterface() *RequestCmdUpdateOne {
	_u.mutation.ClearInterface()
	return _u
}

// SetSuccess sets the "success" field.
func (_u *RequestCmdUpdateOne) SetSuccess(v bool) *RequestCmdUpdateOne {
	_u.mutation.SetSuccess(v)
	return _u
}

// SetNillableSuccess sets the "success" field if the given value is not nil.
func (_u *RequestCmdUpdateOne) SetNillableSuccess(v *bool) *RequestCmdUpdateOne {
	if v != nil {
		_u.SetSuccess(*v)
	}
	return _u
}

// SetError sets the "error" field.
func (_u *RequestCmdUpdateOne) SetError(v string) *RequestCmdUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *RequestCmdUpdateOne) SetNillableError(v *string) *RequestCmdUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *RequestCmdUpdateOne) ClearError() *RequestCmdUpdateOne {
	_u.mutation.ClearError()
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *RequestCmdUpdateOne) SetDurationMs(v int64) *RequestCmdUpdateOne {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *RequestCmdUpdateOne) SetNillableDurationMs(v *int64) *RequestCmdUpdateOne {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *RequestCmdUpdateOne) AddDurationMs(v int64) *RequestCmdUpdateOne {
	_u.mutation.AddDurationMs(v)
	return _u
}

// Mutation returns the RequestCmdMutation object of the builder.
func (_u *RequestCmdUpdateOne) Mutation() *RequestCmdMutation {
	return _u.mutation
}

// Where appends a list predicates to the RequestCmdUpdate builder.
func (_u *RequestCmdUpdateOne) Where(ps ...predicate.RequestCmd) *RequestCmdUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RequestCmdUpdateOne) Select(field string, fields ...string) *RequestCmdUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RequestCmd entity.
func (_u *RequestCmdUpdateOne) Save(ctx context.Context) (*RequestCmd, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequestCmdUpdateOne) SaveX(ctx context.Context) *RequestCmd {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RequestCmdUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequestCmdUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RequestCmdUpdateOne) sqlSave(ctx context.Context) (_node *RequestCmd, err error) {
	_spec := sqlgraph.NewUpdateSpec(requestcmd.Table, requestcmd.Columns, sqlgraph.NewFieldSpec(requestcmd.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RequestCmd.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, requestcmd.FieldID)
		for _, f := range fields {
			if !requestcmd.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != requestcmd.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Timestamp(); ok {
		_spec.SetField(requestcmd.FieldTimestamp, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Command(); ok {
		_spec.SetField(requestcmd.FieldCommand, field.TypeString, value)
	}
	if value, ok := _u.mutation.Args(); ok {
		_spec.SetField(requestcmd.FieldArgs, field.TypeString, value)
	}
	if _u.mutation.ArgsCleared() {
		_spec.ClearField(requestcmd.FieldArgs, field.TypeString)
	}
	if value, ok := _u.mutation.Interface(); ok {
		_spec.SetField(requestcmd.FieldInterface, field.TypeString, value)
	}
	if _u.mutation.InterfaceCleared() {
		_spec.ClearField(requestcmd.FieldInterface, field.TypeString)
	}
	if value, ok := _u.mutation.Success(); ok {
		_spec.SetField(requestcmd.FieldSuccess, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(requestcmd.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(requestcmd.FieldError, field.TypeString)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(requestcmd.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(requestcmd.FieldDurationMs, field.TypeInt64, value)
	}
	_node = &RequestCmd{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{requestcmd.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
