// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-mikrotik-vlan-switcher/ent/predicate"
	"go-mikrotik-vlan-switcher/ent/requestlog"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RequestLogUpdate is the builder for updating RequestLog entities.
type RequestLogUpdate struct {
	config
	hooks    []Hook
	mutation *RequestLogMutation
}

// Where appends a list predicates to the RequestLogUpdate builder.
func (_u *RequestLogUpdate) Where(ps ...predicate.RequestLog) *RequestLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTimestamp sets the "timestamp" field.
func (_u *RequestLogUpdate) SetTimestamp(v time.Time) *RequestLogUpdate {
	_u.mutation.SetTimestamp(v)
	return _u
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableTimestamp(v *time.Time) *RequestLogUpdate {
	if v != nil {
		_u.SetTimestamp(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *RequestLogUpdate) SetMethod(v string) *RequestLogUpdate {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableMethod(v *string) *RequestLogUpdate {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *RequestLogUpdate) SetPath(v string) *RequestLogUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillablePath(v *string) *RequestLogUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetRemoteAddr sets the "remote_addr" field.
func (_u *RequestLogUpdate) SetRemoteAddr(v string) *RequestLogUpdate {
	_u.mutation.SetRemoteAddr(v)
	return _u
}

// SetNillableRemoteAddr sets the "remote_addr" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableRemoteAddr(v *string) *RequestLogUpdate {
	if v != nil {
		_u.SetRemoteAddr(*v)
	}
	return _u
}

// SetSubject sets the "subject" field.
func (_u *RequestLogUpdate) SetSubject(v string) *RequestLogUpdate {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableSubject(v *string) *RequestLogUpdate {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// ClearSubject clears the value of the "subject" field.
func (_u *RequestLogUpdate) ClearSubject() *RequestLogUpdate {
	_u.mutation.ClearSubject()
	return _u
}

// SetInterface sets the "interface" field.
func (_u *RequestLogUpdate) SetInterface(v string) *RequestLogUpdate {
	_u.mutation.SetInterface(v)
	return _u
}

// SetNillableInterface sets the "interface" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableInterface(v *string) *RequestLogUpdate {
	if v != nil {
		_u.SetInterface(*v)
	}
	return _u
}

// ClearInterface clears the value of the "interface" field.
func (_u *RequestLogUpdate) ClearInterface() *RequestLogUpdate {
	_u.mutation.ClearInterface()
	return _u
}

// SetVlanID sets the "vlan_id" field.
func (_u *RequestLogUpdate) SetVlanID(v int) *RequestLogUpdate {
	_u.mutation.ResetVlanID()
	_u.mutation.SetVlanID(v)
	return _u
}

// SetNillableVlanID sets the "vlan_id" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableVlanID(v *int) *RequestLogUpdate {
	if v != nil {
		_u.SetVlanID(*v)
	}
	return _u
}

// AddVlanID adds value to the "vlan_id" field.
func (_u *RequestLogUpdate) AddVlanID(v int) *RequestLogUpdate {
	_u.mutation.AddVlanID(v)
	return _u
}

// ClearVlanID clears the value of the "vlan_id" field.
func (_u *RequestLogUpdate) ClearVlanID() *RequestLogUpdate {
	_u.mutation.ClearVlanID()
	return _u
}

// SetStatusCode sets the "status_code" field.
func (_u *RequestLogUpdate) SetStatusCode(v int) *RequestLogUpdate {
	_u.mutation.ResetStatusCode()
	_u.mutation.SetStatusCode(v)
	return _u
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableStatusCode(v *int) *RequestLogUpdate {
	if v != nil {
		_u.SetStatusCode(*v)
	}
	return _u
}

// AddStatusCode adds value to the "status_code" field.
func (_u *RequestLogUpdate) AddStatusCode(v int) *RequestLogUpdate {
	_u.mutation.AddStatusCode(v)
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *RequestLogUpdate) SetDurationMs(v int64) *RequestLogUpdate {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableDurationMs(v *int64) *RequestLogUpdate {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *RequestLogUpdate) AddDurationMs(v int64) *RequestLogUpdate {
	_u.mutation.AddDurationMs(v)
	return _u
}

// SetError sets the "error" field.
func (_u *RequestLogUpdate) SetError(v string) *RequestLogUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableError(v *string) *RequestLogUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *RequestLogUpdate) ClearError() *RequestLogUpdate {
	_u.mutation.ClearError()
	return _u
}

// Mutation returns the RequestLogMutation object of the builder.
func (_u *RequestLogUpdate) Mutation() *RequestLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RequestLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequestLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RequestLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequestLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RequestLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(requestlog.Table, requestlog.Columns, sqlgraph.NewFieldSpec(requestlog.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Timestamp(); ok {
		_spec.SetField(requestlog.FieldTimestamp, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(requestlog.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(requestlog.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.RemoteAddr(); ok {
		_spec.SetField(requestlog.FieldRemoteAddr, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(requestlog.FieldSubject, field.TypeString, value)
	}
	if _u.mutation.SubjectCleared() {
		_spec.ClearField(requestlog.FieldSubject, field.TypeString)
	}
	if value, ok := _u.mutation.Interface(); ok {
		_spec.SetField(requestlog.FieldInterface, field.TypeString, value)
	}
	if _u.mutation.InterfaceCleared() {
		_spec.ClearField(requestlog.FieldInterface, field.TypeString)
	}
	if value, ok := _u.mutation.VlanID(); ok {
		_spec.SetField(requestlog.FieldVlanID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVlanID(); ok {
		_spec.AddField(requestlog.FieldVlanID, field.TypeInt, value)
	}
	if _u.mutation.VlanIDCleared() {
		_spec.ClearField(requestlog.FieldVlanID, field.TypeInt)
	}
	if value, ok := _u.mutation.StatusCode(); ok {
		_spec.SetField(requestlog.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatusCode(); ok {
		_spec.AddField(requestlog.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(requestlog.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(requestlog.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(requestlog.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(requestlog.FieldError, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{requestlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RequestLogUpdateOne is the builder for updating a single RequestLog entity.
type RequestLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RequestLogMutation
}

// SetTimestamp sets the "timestamp" field.
func (_u *RequestLogUpdateOne) SetTimestamp(v time.Time) *RequestLogUpdateOne {
	_u.mutation.SetTimestamp(v)
	return _u
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableTimestamp(v *time.Time) *RequestLogUpdateOne {
	if v != nil {
		_u.SetTimestamp(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *RequestLogUpdateOne) SetMethod(v string) *RequestLogUpdateOne {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableMethod(v *string) *RequestLogUpdateOne {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *RequestLogUpdateOne) SetPath(v string) *RequestLogUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillablePath(v *string) *RequestLogUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetRemoteAddr sets the "remote_addr" field.
func (_u *RequestLogUpdateOne) SetRemoteAddr(v string) *RequestLogUpdateOne {
	_u.mutation.SetRemoteAddr(v)
	return _u
}

// SetNillableRemoteAddr sets the "remote_addr" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableRemoteAddr(v *string) *RequestLogUpdateOne {
	if v != nil {
		_u.SetRemoteAddr(*v)
	}
	return _u
}

// SetSubject sets the "subject" field.
func (_u *RequestLogUpdateOne) SetSubject(v string) *RequestLogUpdateOne {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableSubject(v *string) *RequestLogUpdateOne {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// ClearSubject clears the value of the "subject" field.
func (_u *RequestLogUpdateOne) ClearSubject() *RequestLogUpdateOne {
	_u.mutation.ClearSubject()
	return _u
}

// SetInterface sets the "interface" field.
func (_u *RequestLogUpdateOne) SetInterface(v string) *RequestLogUpdateOne {
	_u.mutation.SetInterface(v)
	return _u
}

// SetNillableInterface sets the "interface" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableInterface(v *string) *RequestLogUpdateOne {
	if v != nil {
		_u.SetInterface(*v)
	}
	return _u
}

// ClearInterface clears the value of the "interface" field.
func (_u *RequestLogUpdateOne) ClearInterface() *RequestLogUpdateOne {
	_u.mutation.ClearInterface()
	return _u
}

// SetVlanID sets the "vlan_id" field.
func (_u *RequestLogUpdateOne) SetVlanID(v int) *RequestLogUpdateOne {
	_u.mutation.ResetVlanID()
	_u.mutation.SetVlanID(v)
	return _u
}

// SetNillableVlanID sets the "vlan_id" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableVlanID(v *int) *RequestLogUpdateOne {
	if v != nil {
		_u.SetVlanID(*v)
	}
	return _u
}

// AddVlanID adds value to the "vlan_id" field.
func (_u *RequestLogUpdateOne) AddVlanID(v int) *RequestLogUpdateOne {
	_u.mutation.AddVlanID(v)
	return _u
}

// ClearVlanID clears the value of the "vlan_id" field.
func (_u *RequestLogUpdateOne) ClearVlanID() *RequestLogUpdateOne {
	_u.mutation.ClearVlanID()
	return _u
}

// SetStatusCode sets the "status_code" field.
func (_u *RequestLogUpdateOne) SetStatusCode(v int) *RequestLogUpdateOne {
	_u.mutation.ResetStatusCode()
	_u.mutation.SetStatusCode(v)
	return _u
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableStatusCode(v *int) *RequestLogUpdateOne {
	if v != nil {
		_u.SetStatusCode(*v)
	}
	return _u
}

// AddStatusCode adds value to the "status_code" field.
func (_u *RequestLogUpdateOne) AddStatusCode(v int) *RequestLogUpdateOne {
	_u.mutation.AddStatusCode(v)
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *RequestLogUpdateOne) SetDurationMs(v int64) *RequestLogUpdateOne {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableDurationMs(v *int64) *RequestLogUpdateOne {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *RequestLogUpdateOne) AddDurationMs(v int64) *RequestLogUpdateOne {
	_u.mutation.AddDurationMs(v)
	return _u
}

// SetError sets the "error" field.
func (_u *RequestLogUpdateOne) SetError(v string) *RequestLogUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableError(v *string) *RequestLogUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *RequestLogUpdateOne) ClearError() *RequestLogUpdateOne {
	_u.mutation.ClearError()
	return _u
}

// Mutation returns the RequestLogMutation object of the builder.
func (_u *RequestLogUpdateOne) Mutation() *RequestLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the RequestLogUpdate builder.
func (_u *RequestLogUpdateOne) Where(ps ...predicate.RequestLog) *RequestLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RequestLogUpdateOne) Select(field string, fields ...string) *RequestLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RequestLog entity.
func (_u *RequestLogUpdateOne) Save(ctx context.Context) (*RequestLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequestLogUpdateOne) SaveX(ctx context.Context) *RequestLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RequestLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequestLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RequestLogUpdateOne) sqlSave(ctx context.Context) (_node *RequestLog, err error) {
	_spec := sqlgraph.NewUpdateSpec(requestlog.Table, requestlog.Columns, sqlgraph.NewFieldSpec(requestlog.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RequestLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, requestlog.FieldID)
		for _, f := range fields {
			if !requestlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != requestlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Timestamp(); ok {
		_spec.SetField(requestlog.FieldTimestamp, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(requestlog.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(requestlog.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.RemoteAddr(); ok {
		_spec.SetField(requestlog.FieldRemoteAddr, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(requestlog.FieldSubject, field.TypeString, value)
	}
	if _u.mutation.SubjectCleared() {
		_spec.ClearField(requestlog.FieldSubject, field.TypeString)
	}
	if value, ok := _u.mutation.Interface(); ok {
		_spec.SetField(requestlog.FieldInterface, field.TypeString, value)
	}
	if _u.mutation.InterfaceCleared() {
		_spec.ClearField(requestlog.FieldInterface, field.TypeString)
	}
	if value, ok := _u.mutation.VlanID(); ok {
		_spec.SetField(requestlog.FieldVlanID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVlanID(); ok {
		_spec.AddField(requestlog.FieldVlanID, field.TypeInt, value)
	}
	if _u.mutation.VlanIDCleared() {
		_spec.ClearField(requestlog.FieldVlanID, field.TypeInt)
	}
	if value, ok := _u.mutation.StatusCode(); ok {
		_spec.SetField(requestlog.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatusCode(); ok {
		_spec.AddField(requestlog.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(requestlog.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(requestlog.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(requestlog.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(requestlog.FieldError, field.TypeString)
	}
	_node = &RequestLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{requestlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
