// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-mikrotik-vlan-switcher/ent/requestcmd"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RequestCmdCreate is the builder for creating a RequestCmd entity.
type RequestCmdCreate struct {
	config
	mutation *RequestCmdMutation
	hooks    []Hook
}

// SetTimestamp sets the "timestamp" field.
func (_c *RequestCmdCreate) SetTimestamp(v time.Time) *RequestCmdCreate {
	_c.mutation.SetTimestamp(v)
	return _c
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_c *RequestCmdCreate) SetNillableTimestamp(v *time.Time) *RequestCmdCreate {
	if v != nil {
		_c.SetTimestamp(*v)
	}
	return _c
}

// SetCommand sets the "command" field.
func (_c *RequestCmdCreate) SetCommand(v string) *RequestCmdCreate {
	_c.mutation.SetCommand(v)
	return _c
}

// SetArgs sets the "args" field.
func (_c *RequestCmdCreate) SetArgs(v string) *RequestCmdCreate {
	_c.mutation.SetArgs(v)
	return _c
}

// SetNillableArgs sets the "args" field if the given value is not nil.
func (_c *RequestCmdCreate) SetNillableArgs(v *string) *RequestCmdCreate {
	if v != nil {
		_c.SetArgs(*v)
	}
	return _c
}

// SetInterface sets the "interface" field.
func (_c *RequestCmdCreate) SetInterface(v string) *RequestCmdCreate {
	_c.mutation.SetInterface(v)
	return _c
}

// SetNillableInterface sets the "interface" field if the given value is not nil.
func (_c *RequestCmdCreate) SetNillableInterface(v *string) *RequestCmdCreate {
	if v != nil {
		_c.SetInterface(*v)
	}
	return _c
}

// SetSuccess sets the "success" field.
func (_c *RequestCmdCreate) SetSuccess(v bool) *RequestCmdCreate {
	_c.mutation.SetSuccess(v)
	return _c
}

// SetError sets the "error" field.
func (_c *RequestCmdCreate) SetError(v string) *RequestCmdCreate {
	_c.mutation.SetError(v)
	return _c
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_c *RequestCmdCreate) SetNillableError(v *string) *RequestCmdCreate {
	if v != nil {
		_c.SetError(*v)
	}
	return _c
}

// SetDurationMs sets the "duration_ms" field.
func (_c *RequestCmdCreate) SetDurationMs(v int64) *RequestCmdCreate {
	_c.mutation.SetDurationMs(v)
	return _c
}

// Mutation returns the RequestCmdMutation object of the builder.
func (_c *RequestCmdCreate) Mutation() *RequestCmdMutation {
	return _c.mutation
}

// Save creates the RequestCmd in the database.
func (_c *RequestCmdCreate) Save(ctx context.Context) (*RequestCmd, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RequestCmdCreate) SaveX(ctx context.Context) *RequestCmd {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequestCmdCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequestCmdCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RequestCmdCreate) defaults() {
	if _, ok := _c.mutation.Timestamp(); !ok {
		v := requestcmd.DefaultTimestamp()
		_c.mutation.SetTimestamp(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RequestCmdCreate) check() error {
	if _, ok := _c.mutation.Timestamp(); !ok {
		return &ValidationError{Name: "timestamp", err: errors.New(`ent: missing required field "RequestCmd.timestamp"`)}
	}
	if _, ok := _c.mutation.Command(); !ok {
		return &ValidationError{Name: "command", err: errors.New(`ent: missing required field "RequestCmd.command"`)}
	}
	if _, ok := _c.mutation.Success(); !ok {
		return &ValidationError{Name: "success", err: errors.New(`ent: missing required field "RequestCmd.success"`)}
	}
	if _, ok := _c.mutation.DurationMs(); !ok {
		return &ValidationError{Name: "duration_ms", err: errors.New(`ent: missing required field "RequestCmd.duration_ms"`)}
	}
	return nil
}

func (_c *RequestCmdCreate) sqlSave(ctx context.Context) (*RequestCmd, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RequestCmdCreate) createSpec() (*RequestCmd, *sqlgraph.CreateSpec) {
	var (
		_node = &RequestCmd{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(requestcmd.Table, sqlgraph.NewFieldSpec(requestcmd.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Timestamp(); ok {
		_spec.SetField(requestcmd.FieldTimestamp, field.TypeTime, value)
		_node.Timestamp = value
	}
	if value, ok := _c.mutation.Command(); ok {
		_spec.SetField(requestcmd.FieldCommand, field.TypeString, value)
		_node.Command = value
	}
	if value, ok := _c.mutation.Args(); ok {
		_spec.SetField(requestcmd.FieldArgs, field.TypeString, value)
		_node.Args = value
	}
	if value, ok := _c.mutation.Interface(); ok {
		_spec.SetField(requestcmd.FieldInterface, field.TypeString, value)
		_node.Interface = value
	}
	if value, ok := _c.mutation.Success(); ok {
		_spec.SetField(requestcmd.FieldSuccess, field.TypeBool, value)
		_node.Success = value
	}
	if value, ok := _c.mutation.Error(); ok {
		_spec.SetField(requestcmd.FieldError, field.TypeString, value)
		_node.Error = value
	}
	if value, ok := _c.mutation.DurationMs(); ok {
		_spec.SetField(requestcmd.FieldDurationMs, field.TypeInt64, value)
		_node.DurationMs = value
	}
	return _node, _spec
}

// RequestCmdCreateBulk is the builder for creating many RequestCmd entities in bulk.
type RequestCmdCreateBulk struct {
	config
	err      error
	builders []*RequestCmdCreate
}

// Save creates the RequestCmd entities in the database.
func (_c *RequestCmdCreateBulk) Save(ctx context.Context) ([]*RequestCmd, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RequestCmd, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RequestCmdMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RequestCmdCreateBulk) SaveX(ctx context.Context) []*RequestCmd {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequestCmdCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequestCmdCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
