// Code generated by ent, DO NOT EDIT.

package ent

import (
	"go-mikrotik-vlan-switcher/ent/appconfig"
	"go-mikrotik-vlan-switcher/ent/interfacevlanstate"
	"go-mikrotik-vlan-switcher/ent/requestcmd"
	"go-mikrotik-vlan-switcher/ent/requestlog"
	"go-mikrotik-vlan-switcher/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	appconfigFields := schema.AppConfig{}.Fields()
	_ = appconfigFields
	// appconfigDescEnableAuthentication is the schema descriptor for enable_authentication field.
	appconfigDescEnableAuthentication := appconfigFields[6].Descriptor()
	// appconfig.DefaultEnableAuthentication holds the default value on creation for the enable_authentication field.
	appconfig.DefaultEnableAuthentication = appconfigDescEnableAuthentication.Default.(bool)
	interfacevlanstateFields := schema.InterfaceVlanState{}.Fields()
	_ = interfacevlanstateFields
	// interfacevlanstateDescLastSyncedAt is the schema descriptor for last_synced_at field.
	interfacevlanstateDescLastSyncedAt := interfacevlanstateFields[3].Descriptor()
	// interfacevlanstate.DefaultLastSyncedAt holds the default value on creation for the last_synced_at field.
	interfacevlanstate.DefaultLastSyncedAt = interfacevlanstateDescLastSyncedAt.Default.(func() time.Time)
	// interfacevlanstate.UpdateDefaultLastSyncedAt holds the default value on update for the last_synced_at field.
	interfacevlanstate.UpdateDefaultLastSyncedAt = interfacevlanstateDescLastSyncedAt.UpdateDefault.(func() time.Time)
	requestcmdFields := schema.RequestCmd{}.Fields()
	_ = requestcmdFields
	// requestcmdDescTimestamp is the schema descriptor for timestamp field.
	requestcmdDescTimestamp := requestcmdFields[0].Descriptor()
	// requestcmd.DefaultTimestamp holds the default value on creation for the timestamp field.
	requestcmd.DefaultTimestamp = requestcmdDescTimestamp.Default.(func() time.Time)
	requestlogFields := schema.RequestLog{}.Fields()
	_ = requestlogFields
	// requestlogDescTimestamp is the schema descriptor for timestamp field.
	requestlogDescTimestamp := requestlogFields[0].Descriptor()
	// requestlog.DefaultTimestamp holds the default value on creation for the timestamp field.
	requestlog.DefaultTimestamp = requestlogDescTimestamp.Default.(func() time.Time)
}
