// Code generated by ent, DO NOT EDIT.

package requestcmd

import (
	"go-mikrotik-vlan-switcher/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldLTE(FieldID, id))
}

// Timestamp applies equality check predicate on the "timestamp" field. It's identical to TimestampEQ.
func Timestamp(v time.Time) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldEQ(FieldTimestamp, v))
}

// Command applies equality check predicate on the "command" field. It's identical to CommandEQ.
func Command(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldEQ(FieldCommand, v))
}

// Args applies equality check predicate on the "args" field. It's identical to ArgsEQ.
func Args(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldEQ(FieldArgs, v))
}

// Interface applies equality check predicate on the "interface" field. It's identical to InterfaceEQ.
func Interface(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldEQ(FieldInterface, v))
}

// Success applies equality check predicate on the "success" field. It's identical to SuccessEQ.
func Success(v bool) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldEQ(FieldSuccess, v))
}

// Error applies equality check predicate on the "error" field. It's identical to ErrorEQ.
func Error(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldEQ(FieldError, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int64) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldEQ(FieldDurationMs, v))
}

// TimestampEQ applies the EQ predicate on the "timestamp" field.
func TimestampEQ(v time.Time) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldEQ(FieldTimestamp, v))
}

// TimestampNEQ applies the NEQ predicate on the "timestamp" field.
func TimestampNEQ(v time.Time) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldNEQ(FieldTimestamp, v))
}

// TimestampIn applies the In predicate on the "timestamp" field.
func TimestampIn(vs ...time.Time) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldIn(FieldTimestamp, vs...))
}

// TimestampNotIn applies the NotIn predicate on the "timestamp" field.
func TimestampNotIn(vs ...time.Time) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldNotIn(FieldTimestamp, vs...))
}

// TimestampGT applies the GT predicate on the "timestamp" field.
func TimestampGT(v time.Time) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldGT(FieldTimestamp, v))
}

// TimestampGTE applies the GTE predicate on the "timestamp" field.
func TimestampGTE(v time.Time) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldGTE(FieldTimestamp, v))
}

// TimestampLT applies the LT predicate on the "timestamp" field.
func TimestampLT(v time.Time) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldLT(FieldTimestamp, v))
}

// TimestampLTE applies the LTE predicate on the "timestamp" field.
func TimestampLTE(v time.Time) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldLTE(FieldTimestamp, v))
}

// CommandEQ applies the EQ predicate on the "command" field.
func CommandEQ(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldEQ(FieldCommand, v))
}

// CommandNEQ applies the NEQ predicate on the "command" field.
func CommandNEQ(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldNEQ(FieldCommand, v))
}

// CommandIn applies the In predicate on the "command" field.
func CommandIn(vs ...string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldIn(FieldCommand, vs...))
}

// CommandNotIn applies the NotIn predicate on the "command" field.
func CommandNotIn(vs ...string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldNotIn(FieldCommand, vs...))
}

// CommandGT applies the GT predicate on the "command" field.
func CommandGT(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldGT(FieldCommand, v))
}

// CommandGTE applies the GTE predicate on the "command" field.
func CommandGTE(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldGTE(FieldCommand, v))
}

// CommandLT applies the LT predicate on the "command" field.
func CommandLT(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldLT(FieldCommand, v))
}

// CommandLTE applies the LTE predicate on the "command" field.
func CommandLTE(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldLTE(FieldCommand, v))
}

// CommandContains applies the Contains predicate on the "command" field.
func CommandContains(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldContains(FieldCommand, v))
}

// CommandHasPrefix applies the HasPrefix predicate on the "command" field.
func CommandHasPrefix(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldHasPrefix(FieldCommand, v))
}

// CommandHasSuffix applies the HasSuffix predicate on the "command" field.
func CommandHasSuffix(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldHasSuffix(FieldCommand, v))
}

// CommandEqualFold applies the EqualFold predicate on the "command" field.
func CommandEqualFold(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldEqualFold(FieldCommand, v))
}

// CommandContainsFold applies the ContainsFold predicate on the "command" field.
func CommandContainsFold(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldContainsFold(FieldCommand, v))
}

// ArgsEQ applies the EQ predicate on the "args" field.
func ArgsEQ(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldEQ(FieldArgs, v))
}

// ArgsNEQ applies the NEQ predicate on the "args" field.
func ArgsNEQ(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldNEQ(FieldArgs, v))
}

// ArgsIn applies the In predicate on the "args" field.
func ArgsIn(vs ...string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldIn(FieldArgs, vs...))
}

// ArgsNotIn applies the NotIn predicate on the "args" field.
func ArgsNotIn(vs ...string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldNotIn(FieldArgs, vs...))
}

// ArgsGT applies the GT predicate on the "args" field.
func ArgsGT(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldGT(FieldArgs, v))
}

// ArgsGTE applies the GTE predicate on the "args" field.
func ArgsGTE(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldGTE(FieldArgs, v))
}

// ArgsLT applies the LT predicate on the "args" field.
func ArgsLT(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldLT(FieldArgs, v))
}

// ArgsLTE applies the LTE predicate on the "args" field.
func ArgsLTE(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldLTE(FieldArgs, v))
}

// ArgsContains applies the Contains predicate on the "args" field.
func ArgsContains(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldContains(FieldArgs, v))
}

// ArgsHasPrefix applies the HasPrefix predicate on the "args" field.
func ArgsHasPrefix(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldHasPrefix(FieldArgs, v))
}

// ArgsHasSuffix applies the HasSuffix predicate on the "args" field.
func ArgsHasSuffix(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldHasSuffix(FieldArgs, v))
}

// ArgsIsNil applies the IsNil predicate on the "args" field.
func ArgsIsNil() predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldIsNull(FieldArgs))
}

// ArgsNotNil applies the NotNil predicate on the "args" field.
func ArgsNotNil() predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldNotNull(FieldArgs))
}

// ArgsEqualFold applies the EqualFold predicate on the "args" field.
func ArgsEqualFold(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldEqualFold(FieldArgs, v))
}

// ArgsContainsFold applies the ContainsFold predicate on the "args" field.
func ArgsContainsFold(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldContainsFold(FieldArgs, v))
}

// InterfaceEQ applies the EQ predicate on the "interface" field.
func InterfaceEQ(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldEQ(FieldInterface, v))
}

// InterfaceNEQ applies the NEQ predicate on the "interface" field.
func InterfaceNEQ(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldNEQ(FieldInterface, v))
}

// InterfaceIn applies the In predicate on the "interface" field.
func InterfaceIn(vs ...string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldIn(FieldInterface, vs...))
}

// InterfaceNotIn applies the NotIn predicate on the "interface" field.
func InterfaceNotIn(vs ...string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldNotIn(FieldInterface, vs...))
}

// InterfaceGT applies the GT predicate on the "interface" field.
func InterfaceGT(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldGT(FieldInterface, v))
}

// InterfaceGTE applies the GTE predicate on the "interface" field.
func InterfaceGTE(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldGTE(FieldInterface, v))
}

// InterfaceLT applies the LT predicate on the "interface" field.
func InterfaceLT(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldLT(FieldInterface, v))
}

// InterfaceLTE applies the LTE predicate on the "interface" field.
func InterfaceLTE(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldLTE(FieldInterface, v))
}

// InterfaceContains applies the Contains predicate on the "interface" field.
func InterfaceContains(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldContains(FieldInterface, v))
}

// InterfaceHasPrefix applies the HasPrefix predicate on the "interface" field.
func InterfaceHasPrefix(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldHasPrefix(FieldInterface, v))
}

// InterfaceHasSuffix applies the HasSuffix predicate on the "interface" field.
func InterfaceHasSuffix(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldHasSuffix(FieldInterface, v))
}

// InterfaceIsNil applies the IsNil predicate on the "interface" field.
func InterfaceIsNil() predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldIsNull(FieldInterface))
}

// InterfaceNotNil applies the NotNil predicate on the "interface" field.
func InterfaceNotNil() predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldNotNull(FieldInterface))
}

// InterfaceEqualFold applies the EqualFold predicate on the "interface" field.
func InterfaceEqualFold(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldEqualFold(FieldInterface, v))
}

// InterfaceContainsFold applies the ContainsFold predicate on the "interface" field.
func InterfaceContainsFold(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldContainsFold(FieldInterface, v))
}

// SuccessEQ applies the EQ predicate on the "success" field.
func SuccessEQ(v bool) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldEQ(FieldSuccess, v))
}

// SuccessNEQ applies the NEQ predicate on the "success" field.
func SuccessNEQ(v bool) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldNEQ(FieldSuccess, v))
}

// ErrorEQ applies the EQ predicate on the "error" field.
func ErrorEQ(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldEQ(FieldError, v))
}

// ErrorNEQ applies the NEQ predicate on the "error" field.
func ErrorNEQ(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldNEQ(FieldError, v))
}

// ErrorIn applies the In predicate on the "error" field.
func ErrorIn(vs ...string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldIn(FieldError, vs...))
}

// ErrorNotIn applies the NotIn predicate on the "error" field.
func ErrorNotIn(vs ...string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldNotIn(FieldError, vs...))
}

// ErrorGT applies the GT predicate on the "error" field.
func ErrorGT(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldGT(FieldError, v))
}

// ErrorGTE applies the GTE predicate on the "error" field.
func ErrorGTE(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldGTE(FieldError, v))
}

// ErrorLT applies the LT predicate on the "error" field.
func ErrorLT(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldLT(FieldError, v))
}

// ErrorLTE applies the LTE predicate on the "error" field.
func ErrorLTE(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldLTE(FieldError, v))
}

// ErrorContains applies the Contains predicate on the "error" field.
func ErrorContains(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldContains(FieldError, v))
}

// ErrorHasPrefix applies the HasPrefix predicate on the "error" field.
func ErrorHasPrefix(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldHasPrefix(FieldError, v))
}

// ErrorHasSuffix applies the HasSuffix predicate on the "error" field.
func ErrorHasSuffix(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldHasSuffix(FieldError, v))
}

// ErrorIsNil applies the IsNil predicate on the "error" field.
func ErrorIsNil() predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldIsNull(FieldError))
}

// ErrorNotNil applies the NotNil predicate on the "error" field.
func ErrorNotNil() predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldNotNull(FieldError))
}

// ErrorEqualFold applies the EqualFold predicate on the "error" field.
func ErrorEqualFold(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldEqualFold(FieldError, v))
}

// ErrorContainsFold applies the ContainsFold predicate on the "error" field.
func ErrorContainsFold(v string) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldContainsFold(FieldError, v))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int64) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int64) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int64) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int64) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int64) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int64) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int64) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int64) predicate.RequestCmd {
	return predicate.RequestCmd(sql.FieldLTE(FieldDurationMs, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RequestCmd) predicate.RequestCmd {
	return predicate.RequestCmd(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RequestCmd) predicate.RequestCmd {
	return predicate.RequestCmd(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RequestCmd) predicate.RequestCmd {
	return predicate.RequestCmd(sql.NotPredicates(p))
}
