// Code generated by ent, DO NOT EDIT.

package requestlog

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the requestlog type in the database.
	Label = "request_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTimestamp holds the string denoting the timestamp field in the database.
	FieldTimestamp = "timestamp"
	// FieldMethod holds the string denoting the method field in the database.
	FieldMethod = "method"
	// FieldPath holds the string denoting the path field in the database.
	FieldPath = "path"
	// FieldRemoteAddr holds the string denoting the remote_addr field in the database.
	FieldRemoteAddr = "remote_addr"
	// FieldSubject holds the string denoting the subject field in the database.
	FieldSubject = "subject"
	// FieldInterface holds the string denoting the interface field in the database.
	FieldInterface = "interface"
	// FieldVlanID holds the string denoting the vlan_id field in the database.
	FieldVlanID = "vlan_id"
	// FieldStatusCode holds the string denoting the status_code field in the database.
	FieldStatusCode = "status_code"
	// FieldDurationMs holds the string denoting the duration_ms field in the database.
	FieldDurationMs = "duration_ms"
	// FieldError holds the string denoting the error field in the database.
	FieldError = "error"
	// Table holds the table name of the requestlog in the database.
	Table = "request_logs"
)

// Columns holds all SQL columns for requestlog fields.
var Columns = []string{
	FieldID,
	FieldTimestamp,
	FieldMethod,
	FieldPath,
	FieldRemoteAddr,
	FieldSubject,
	FieldInterface,
	FieldVlanID,
	FieldStatusCode,
	FieldDurationMs,
	FieldError,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTimestamp holds the default value on creation for the "timestamp" field.
	DefaultTimestamp func() time.Time
)

// OrderOption defines the ordering options for the RequestLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTimestamp orders the results by the timestamp field.
func ByTimestamp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimestamp, opts...).ToFunc()
}

// ByMethod orders the results by the method field.
func ByMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMethod, opts...).ToFunc()
}

// ByPath orders the results by the path field.
func ByPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPath, opts...).ToFunc()
}

// ByRemoteAddr orders the results by the remote_addr field.
func ByRemoteAddr(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemoteAddr, opts...).ToFunc()
}

// BySubject orders the results by the subject field.
func BySubject(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubject, opts...).ToFunc()
}

// ByInterface orders the results by the interface field.
func ByInterface(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInterface, opts...).ToFunc()
}

// ByVlanID orders the results by the vlan_id field.
func ByVlanID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVlanID, opts...).ToFunc()
}

// ByStatusCode orders the results by the status_code field.
func ByStatusCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatusCode, opts...).ToFunc()
}

// ByDurationMs orders the results by the duration_ms field.
func ByDurationMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDurationMs, opts...).ToFunc()
}

// ByError orders the results by the error field.
func ByError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldError, opts...).ToFunc()
}
