// Code generated by ent, DO NOT EDIT.

package requestlog

import (
	"go-mikrotik-vlan-switcher/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLTE(FieldID, id))
}

// Timestamp applies equality check predicate on the "timestamp" field. It's identical to TimestampEQ.
func Timestamp(v time.Time) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldTimestamp, v))
}

// Method applies equality check predicate on the "method" field. It's identical to MethodEQ.
func Method(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldMethod, v))
}

// Path applies equality check predicate on the "path" field. It's identical to PathEQ.
func Path(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldPath, v))
}

// RemoteAddr applies equality check predicate on the "remote_addr" field. It's identical to RemoteAddrEQ.
func RemoteAddr(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldRemoteAddr, v))
}

// Subject applies equality check predicate on the "subject" field. It's identical to SubjectEQ.
func Subject(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldSubject, v))
}

// Interface applies equality check predicate on the "interface" field. It's identical to InterfaceEQ.
func Interface(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldInterface, v))
}

// VlanID applies equality check predicate on the "vlan_id" field. It's identical to VlanIDEQ.
func VlanID(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldVlanID, v))
}

// StatusCode applies equality check predicate on the "status_code" field. It's identical to StatusCodeEQ.
func StatusCode(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldStatusCode, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int64) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldDurationMs, v))
}

// Error applies equality check predicate on the "error" field. It's identical to ErrorEQ.
func Error(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldError, v))
}

// TimestampEQ applies the EQ predicate on the "timestamp" field.
func TimestampEQ(v time.Time) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldTimestamp, v))
}

// TimestampNEQ applies the NEQ predicate on the "timestamp" field.
func TimestampNEQ(v time.Time) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNEQ(FieldTimestamp, v))
}

// TimestampIn applies the In predicate on the "timestamp" field.
func TimestampIn(vs ...time.Time) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIn(FieldTimestamp, vs...))
}

// TimestampNotIn applies the NotIn predicate on the "timestamp" field.
func TimestampNotIn(vs ...time.Time) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotIn(FieldTimestamp, vs...))
}

// TimestampGT applies the GT predicate on the "timestamp" field.
func TimestampGT(v time.Time) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGT(FieldTimestamp, v))
}

// TimestampGTE applies the GTE predicate on the "timestamp" field.
func TimestampGTE(v time.Time) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGTE(FieldTimestamp, v))
}

// TimestampLT applies the LT predicate on the "timestamp" field.
func TimestampLT(v time.Time) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLT(FieldTimestamp, v))
}

// TimestampLTE applies the LTE predicate on the "timestamp" field.
func TimestampLTE(v time.Time) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLTE(FieldTimestamp, v))
}

// MethodEQ applies the EQ predicate on the "method" field.
func MethodEQ(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldMethod, v))
}

// MethodNEQ applies the NEQ predicate on the "method" field.
func MethodNEQ(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNEQ(FieldMethod, v))
}

// MethodIn applies the In predicate on the "method" field.
func MethodIn(vs ...string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIn(FieldMethod, vs...))
}

// MethodNotIn applies the NotIn predicate on the "method" field.
func MethodNotIn(vs ...string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotIn(FieldMethod, vs...))
}

// MethodGT applies the GT predicate on the "method" field.
func MethodGT(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGT(FieldMethod, v))
}

// MethodGTE applies the GTE predicate on the "method" field.
func MethodGTE(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGTE(FieldMethod, v))
}

// MethodLT applies the LT predicate on the "method" field.
func MethodLT(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLT(FieldMethod, v))
}

// MethodLTE applies the LTE predicate on the "method" field.
func MethodLTE(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLTE(FieldMethod, v))
}

// MethodContains applies the Contains predicate on the "method" field.
func MethodContains(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldContains(FieldMethod, v))
}

// MethodHasPrefix applies the HasPrefix predicate on the "method" field.
func MethodHasPrefix(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldHasPrefix(FieldMethod, v))
}

// MethodHasSuffix applies the HasSuffix predicate on the "method" field.
func MethodHasSuffix(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldHasSuffix(FieldMethod, v))
}

// MethodEqualFold applies the EqualFold predicate on the "method" field.
func MethodEqualFold(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEqualFold(FieldMethod, v))
}

// MethodContainsFold applies the ContainsFold predicate on the "method" field.
func MethodContainsFold(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldContainsFold(FieldMethod, v))
}

// PathEQ applies the EQ predicate on the "path" field.
func PathEQ(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldPath, v))
}

// PathNEQ applies the NEQ predicate on the "path" field.
func PathNEQ(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNEQ(FieldPath, v))
}

// PathIn applies the In predicate on the "path" field.
func PathIn(vs ...string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIn(FieldPath, vs...))
}

// PathNotIn applies the NotIn predicate on the "path" field.
func PathNotIn(vs ...string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotIn(FieldPath, vs...))
}

// PathGT applies the GT predicate on the "path" field.
func PathGT(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGT(FieldPath, v))
}

// PathGTE applies the GTE predicate on the "path" field.
func PathGTE(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGTE(FieldPath, v))
}

// PathLT applies the LT predicate on the "path" field.
func PathLT(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLT(FieldPath, v))
}

// PathLTE applies the LTE predicate on the "path" field.
func PathLTE(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLTE(FieldPath, v))
}

// PathContains applies the Contains predicate on the "path" field.
func PathContains(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldContains(FieldPath, v))
}

// PathHasPrefix applies the HasPrefix predicate on the "path" field.
func PathHasPrefix(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldHasPrefix(FieldPath, v))
}

// PathHasSuffix applies the HasSuffix predicate on the "path" field.
func PathHasSuffix(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldHasSuffix(FieldPath, v))
}

// PathEqualFold applies the EqualFold predicate on the "path" field.
func PathEqualFold(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEqualFold(FieldPath, v))
}

// PathContainsFold applies the ContainsFold predicate on the "path" field.
func PathContainsFold(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldContainsFold(FieldPath, v))
}

// RemoteAddrEQ applies the EQ predicate on the "remote_addr" field.
func RemoteAddrEQ(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldRemoteAddr, v))
}

// RemoteAddrNEQ applies the NEQ predicate on the "remote_addr" field.
func RemoteAddrNEQ(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNEQ(FieldRemoteAddr, v))
}

// RemoteAddrIn applies the In predicate on the "remote_addr" field.
func RemoteAddrIn(vs ...string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIn(FieldRemoteAddr, vs...))
}

// RemoteAddrNotIn applies the NotIn predicate on the "remote_addr" field.
func RemoteAddrNotIn(vs ...string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotIn(FieldRemoteAddr, vs...))
}

// RemoteAddrGT applies the GT predicate on the "remote_addr" field.
func RemoteAddrGT(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGT(FieldRemoteAddr, v))
}

// RemoteAddrGTE applies the GTE predicate on the "remote_addr" field.
func RemoteAddrGTE(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGTE(FieldRemoteAddr, v))
}

// RemoteAddrLT applies the LT predicate on the "remote_addr" field.
func RemoteAddrLT(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLT(FieldRemoteAddr, v))
}

// RemoteAddrLTE applies the LTE predicate on the "remote_addr" field.
func RemoteAddrLTE(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLTE(FieldRemoteAddr, v))
}

// RemoteAddrContains applies the Contains predicate on the "remote_addr" field.
func RemoteAddrContains(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldContains(FieldRemoteAddr, v))
}

// RemoteAddrHasPrefix applies the HasPrefix predicate on the "remote_addr" field.
func RemoteAddrHasPrefix(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldHasPrefix(FieldRemoteAddr, v))
}

// RemoteAddrHasSuffix applies the HasSuffix predicate on the "remote_addr" field.
func RemoteAddrHasSuffix(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldHasSuffix(FieldRemoteAddr, v))
}

// RemoteAddrEqualFold applies the EqualFold predicate on the "remote_addr" field.
func RemoteAddrEqualFold(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEqualFold(FieldRemoteAddr, v))
}

// RemoteAddrContainsFold applies the ContainsFold predicate on the "remote_addr" field.
func RemoteAddrContainsFold(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldContainsFold(FieldRemoteAddr, v))
}

// SubjectEQ applies the EQ predicate on the "subject" field.
func SubjectEQ(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldSubject, v))
}

// SubjectNEQ applies the NEQ predicate on the "subject" field.
func SubjectNEQ(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNEQ(FieldSubject, v))
}

// SubjectIn applies the In predicate on the "subject" field.
func SubjectIn(vs ...string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIn(FieldSubject, vs...))
}

// SubjectNotIn applies the NotIn predicate on the "subject" field.
func SubjectNotIn(vs ...string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotIn(FieldSubject, vs...))
}

// SubjectGT applies the GT predicate on the "subject" field.
func SubjectGT(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGT(FieldSubject, v))
}

// SubjectGTE applies the GTE predicate on the "subject" field.
func SubjectGTE(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGTE(FieldSubject, v))
}

// SubjectLT applies the LT predicate on the "subject" field.
func SubjectLT(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLT(FieldSubject, v))
}

// SubjectLTE applies the LTE predicate on the "subject" field.
func SubjectLTE(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLTE(FieldSubject, v))
}

// SubjectContains applies the Contains predicate on the "subject" field.
func SubjectContains(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldContains(FieldSubject, v))
}

// SubjectHasPrefix applies the HasPrefix predicate on the "subject" field.
func SubjectHasPrefix(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldHasPrefix(FieldSubject, v))
}

// SubjectHasSuffix applies the HasSuffix predicate on the "subject" field.
func SubjectHasSuffix(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldHasSuffix(FieldSubject, v))
}

// SubjectIsNil applies the IsNil predicate on the "subject" field.
func SubjectIsNil() predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIsNull(FieldSubject))
}

// SubjectNotNil applies the NotNil predicate on the "subject" field.
func SubjectNotNil() predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotNull(FieldSubject))
}

// SubjectEqualFold applies the EqualFold predicate on the "subject" field.
func SubjectEqualFold(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEqualFold(FieldSubject, v))
}

// SubjectContainsFold applies the ContainsFold predicate on the "subject" field.
func SubjectContainsFold(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldContainsFold(FieldSubject, v))
}

// InterfaceEQ applies the EQ predicate on the "interface" field.
func InterfaceEQ(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldInterface, v))
}

// InterfaceNEQ applies the NEQ predicate on the "interface" field.
func InterfaceNEQ(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNEQ(FieldInterface, v))
}

// InterfaceIn applies the In predicate on the "interface" field.
func InterfaceIn(vs ...string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIn(FieldInterface, vs...))
}

// InterfaceNotIn applies the NotIn predicate on the "interface" field.
func InterfaceNotIn(vs ...string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotIn(FieldInterface, vs...))
}

// InterfaceGT applies the GT predicate on the "interface" field.
func InterfaceGT(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGT(FieldInterface, v))
}

// InterfaceGTE applies the GTE predicate on the "interface" field.
func InterfaceGTE(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGTE(FieldInterface, v))
}

// InterfaceLT applies the LT predicate on the "interface" field.
func InterfaceLT(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLT(FieldInterface, v))
}

// InterfaceLTE applies the LTE predicate on the "interface" field.
func InterfaceLTE(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLTE(FieldInterface, v))
}

// InterfaceContains applies the Contains predicate on the "interface" field.
func InterfaceContains(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldContains(FieldInterface, v))
}

// InterfaceHasPrefix applies the HasPrefix predicate on the "interface" field.
func InterfaceHasPrefix(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldHasPrefix(FieldInterface, v))
}

// InterfaceHasSuffix applies the HasSuffix predicate on the "interface" field.
func InterfaceHasSuffix(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldHasSuffix(FieldInterface, v))
}

// InterfaceIsNil applies the IsNil predicate on the "interface" field.
func InterfaceIsNil() predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIsNull(FieldInterface))
}

// InterfaceNotNil applies the NotNil predicate on the "interface" field.
func InterfaceNotNil() predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotNull(FieldInterface))
}

// InterfaceEqualFold applies the EqualFold predicate on the "interface" field.
func InterfaceEqualFold(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEqualFold(FieldInterface, v))
}

// InterfaceContainsFold applies the ContainsFold predicate on the "interface" field.
func InterfaceContainsFold(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldContainsFold(FieldInterface, v))
}

// VlanIDEQ applies the EQ predicate on the "vlan_id" field.
func VlanIDEQ(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldVlanID, v))
}

// VlanIDNEQ applies the NEQ predicate on the "vlan_id" field.
func VlanIDNEQ(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNEQ(FieldVlanID, v))
}

// VlanIDIn applies the In predicate on the "vlan_id" field.
func VlanIDIn(vs ...int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIn(FieldVlanID, vs...))
}

// VlanIDNotIn applies the NotIn predicate on the "vlan_id" field.
func VlanIDNotIn(vs ...int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotIn(FieldVlanID, vs...))
}

// VlanIDGT applies the GT predicate on the "vlan_id" field.
func VlanIDGT(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGT(FieldVlanID, v))
}

// VlanIDGTE applies the GTE predicate on the "vlan_id" field.
func VlanIDGTE(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGTE(FieldVlanID, v))
}

// VlanIDLT applies the LT predicate on the "vlan_id" field.
func VlanIDLT(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLT(FieldVlanID, v))
}

// VlanIDLTE applies the LTE predicate on the "vlan_id" field.
func VlanIDLTE(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLTE(FieldVlanID, v))
}

// VlanIDIsNil applies the IsNil predicate on the "vlan_id" field.
func VlanIDIsNil() predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIsNull(FieldVlanID))
}

// VlanIDNotNil applies the NotNil predicate on the "vlan_id" field.
func VlanIDNotNil() predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotNull(FieldVlanID))
}

// StatusCodeEQ applies the EQ predicate on the "status_code" field.
func StatusCodeEQ(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldStatusCode, v))
}

// StatusCodeNEQ applies the NEQ predicate on the "status_code" field.
func StatusCodeNEQ(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNEQ(FieldStatusCode, v))
}

// StatusCodeIn applies the In predicate on the "status_code" field.
func StatusCodeIn(vs ...int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIn(FieldStatusCode, vs...))
}

// StatusCodeNotIn applies the NotIn predicate on the "status_code" field.
func StatusCodeNotIn(vs ...int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotIn(FieldStatusCode, vs...))
}

// StatusCodeGT applies the GT predicate on the "status_code" field.
func StatusCodeGT(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGT(FieldStatusCode, v))
}

// StatusCodeGTE applies the GTE predicate on the "status_code" field.
func StatusCodeGTE(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGTE(FieldStatusCode, v))
}

// StatusCodeLT applies the LT predicate on the "status_code" field.
func StatusCodeLT(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLT(FieldStatusCode, v))
}

// StatusCodeLTE applies the LTE predicate on the "status_code" field.
func StatusCodeLTE(v int) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLTE(FieldStatusCode, v))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int64) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int64) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int64) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int64) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int64) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int64) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int64) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int64) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLTE(FieldDurationMs, v))
}

// ErrorEQ applies the EQ predicate on the "error" field.
func ErrorEQ(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEQ(FieldError, v))
}

// ErrorNEQ applies the NEQ predicate on the "error" field.
func ErrorNEQ(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNEQ(FieldError, v))
}

// ErrorIn applies the In predicate on the "error" field.
func ErrorIn(vs ...string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIn(FieldError, vs...))
}

// ErrorNotIn applies the NotIn predicate on the "error" field.
func ErrorNotIn(vs ...string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotIn(FieldError, vs...))
}

// ErrorGT applies the GT predicate on the "error" field.
func ErrorGT(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGT(FieldError, v))
}

// ErrorGTE applies the GTE predicate on the "error" field.
func ErrorGTE(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldGTE(FieldError, v))
}

// ErrorLT applies the LT predicate on the "error" field.
func ErrorLT(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLT(FieldError, v))
}

// ErrorLTE applies the LTE predicate on the "error" field.
func ErrorLTE(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldLTE(FieldError, v))
}

// ErrorContains applies the Contains predicate on the "error" field.
func ErrorContains(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldContains(FieldError, v))
}

// ErrorHasPrefix applies the HasPrefix predicate on the "error" field.
func ErrorHasPrefix(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldHasPrefix(FieldError, v))
}

// ErrorHasSuffix applies the HasSuffix predicate on the "error" field.
func ErrorHasSuffix(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldHasSuffix(FieldError, v))
}

// ErrorIsNil applies the IsNil predicate on the "error" field.
func ErrorIsNil() predicate.RequestLog {
	return predicate.RequestLog(sql.FieldIsNull(FieldError))
}

// ErrorNotNil applies the NotNil predicate on the "error" field.
func ErrorNotNil() predicate.RequestLog {
	return predicate.RequestLog(sql.FieldNotNull(FieldError))
}

// ErrorEqualFold applies the EqualFold predicate on the "error" field.
func ErrorEqualFold(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldEqualFold(FieldError, v))
}

// ErrorContainsFold applies the ContainsFold predicate on the "error" field.
func ErrorContainsFold(v string) predicate.RequestLog {
	return predicate.RequestLog(sql.FieldContainsFold(FieldError, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RequestLog) predicate.RequestLog {
	return predicate.RequestLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RequestLog) predicate.RequestLog {
	return predicate.RequestLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RequestLog) predicate.RequestLog {
	return predicate.RequestLog(sql.NotPredicates(p))
}
